// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Core.Models.Entities
{
    using Tmpi.Pyrene.Core.Models.Enums;

    // CompteurValeur
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class CompteurValeur
    {
        public int CleCompteur { get; set; } // CleCompteur (Primary key)
        public int ValPeriode { get; set; } // ValPeriode (Primary key)
        public int ValCompteur { get; set; } // ValCompteur

        // Foreign keys
        [Newtonsoft.Json.JsonIgnore]
        public virtual Compteur Compteur { get; set; } // FK_CompteurValeur_CleCompteur
    }

}
// </auto-generated>
