//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[CompositeIndex(true, nameof(CleCompteur), nameof(ValPeriode))]
    [Route("/Compteur/{CodCompteur}/Valeur/{ValPeriode}", HttpVerbs.Post, Summary = "Ajoute une ressource GenCompteurValeur.")]
    [Route("/Compteur/{CodCompteur}/Valeur/{ValPeriode}", HttpVerbs.Put, Summary = "Remplace une ressource GenCompteurValeur à partir de son Id.")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource GenCompteurValeur spécifiée est introuvable.")]
	public partial class GenCompteurValeur
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[AutoIncrement]
		[PrimaryKey]
        [IgnoreDataMember]
		public int CleValeur { get; set; }

		/// <summary>
		/// Compteur parent.
		/// </summary>
		[ForeignKey(typeof(GenCompteur), OnDelete = "CASCADE")]
		[Required]
        [IgnoreDataMember]
		public int CleCompteur { get; set; }

		/// <summary>
		/// Valeur de la période.
		/// </summary>
		[Required]
		[ApiMember(Description = "Valeur de la période.", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int ValPeriode { get; set; }

		/// <summary>
		/// Valeur du compteur.
		/// </summary>
		[Required]
		[ApiMember(Description = "Valeur du compteur.", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int ValCompteur { get; set; }

	}
}
