//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[CompositeIndex(true, nameof(CleCompteurProprio), nameof(ValPeriode))]
    [Route("/Compteur/{CodCompteurProprio}/Valeur/{ValPeriode}", HttpVerbs.Post, Summary = "Ajoute une ressource GenCompteurValeur.")]
    [Route("/Compteur/{CodCompteurProprio}/Valeur/{ValPeriode}", HttpVerbs.Put, Summary = "Remplace une ressource GenCompteurValeur.")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource GenCompteurValeur spécifiée est introuvable.")]
	public partial class GenCompteurValeur
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[AutoIncrement]
		[PrimaryKey]
        [IgnoreDataMember]
		public int CleValeur { get; set; }

		/// <summary>
		/// Compteur parent.
		/// </summary>
		[ForeignKey(typeof(GenCompteur), OnDelete = "CASCADE")]
		[Required]
        [IgnoreDataMember]
		public int CleCompteurProprio { get; set; }

		/// <summary>
		/// Compteur parent. Code unique.
		/// </summary>
        /// <remarks>
		/// Remplace la propriété <see cref="CleCompteurProprio" /> dans la sérialisation.
		/// Référence la propriété <see cref="GenCompteur.CodCompteur" />.
        /// </remarks>
		[ApiMember(Description = "Compteur parent. Code unique.", DataType = SwaggerDataTypes.String, IsRequired = true)]
		[Ignore]
		public string CodCompteurProprio { get; set; }

		/// <summary>
		/// Valeur de la période.
		/// </summary>
		[Required]
		[Index(true)]
		[ApiMember(Description = "Valeur de la période.", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int ValPeriode { get; set; }

		/// <summary>
		/// Valeur du compteur.
		/// </summary>
		[Required]
		[ApiMember(Description = "Valeur du compteur.", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int ValCompteur { get; set; }

		[Reference]
		public List<GenCompteurValeurTruc> LstTruc { get; set; }

	}
}
