//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
    [Route("/Compteur/{CodCompteurProprio}/Valeur/{ValPeriode}/Truc", HttpVerbs.Post, Summary = "Ajoute une ressource GenCompteurValeurTruc.")]
    [Route("/Compteur/{CodCompteurProprio}/Valeur/{ValPeriode}/Truc/{CleTruc}", HttpVerbs.Put, Summary = "Remplace une ressource GenCompteurValeurTruc à partir de son Id.")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource GenCompteurValeurTruc spécifiée est introuvable.")]
	public partial class GenCompteurValeurTruc
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[AutoIncrement]
		[PrimaryKey]
        [IgnoreDataMember]
		public int CleTruc { get; set; }

		[ForeignKey(typeof(GenCompteurValeurTruc), OnDelete = "CASCADE")]
		[Required]
        [IgnoreDataMember]
		public int CleValeur { get; set; }

		/// <summary>
		/// Valeur de la période.
		/// Remplace la colonne <see cref="CleValeur" /> dans la sérialisation.
		/// </summary>
		[ApiMember(Description = "Valeur de la période.", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		[Ignore]
		public int ValPeriode { get; set; }

		[StringLength(500)]
		[ApiMember(DataType = SwaggerDataTypes.String)]
		public string TxtMachin { get; set; }

		[Reference]
		public GenCompteurValeurTruc  { get; set; }

	}
}
