//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[CompositeIndex(true, nameof(CleGenFourn), nameof(CodIBAN))]
	public partial class GenFournBanque : IHasId<int>,
		IAuditable
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[AutoIncrement]
		[ApiMember(Description = "Clé primaire.", DataType = SwaggerType.Int)]
		public int Id { get; set; }

		/// <summary>
		/// Id du fournisseur parent.
		/// </summary>
		[ForeignKey(typeof(GenFourn), OnDelete = "CASCADE")]
		[Required]
		[ApiMember(Description = "Id du fournisseur parent.", IsRequired = true, DataType = SwaggerType.Int)]
		public int CleGenFourn { get; set; }

		/// <summary>
		/// Code IBAN.
		/// </summary>
		[StringLength(34)]
		[Required]
		[ApiMember(Description = "Code IBAN.", IsRequired = true, DataType = SwaggerType.String)]
		public string CodIBAN { get; set; }

		/// <summary>
		/// Code BIC.
		/// </summary>
		[StringLength(11)]
		[Required]
		[ApiMember(Description = "Code BIC.", IsRequired = true, DataType = SwaggerType.String)]
		public string CodBIC { get; set; }

		/// <summary>
		/// Nom de l'établissement bancaire.
		/// </summary>
		[StringLength(200)]
		[Required]
		[ApiMember(Description = "Nom de l'établissement bancaire.", IsRequired = true, DataType = SwaggerType.String)]
		public string LibEtablissement { get; set; }

		/// <summary>
		/// Si true, les coordonnées bancaires sont celles par défaut pour le fournisseur.
		/// </summary>
		[Required]
		[ApiMember(Description = "Si true, les coordonnées bancaires sont celles par défaut pour le fournisseur.", IsRequired = true, DataType = SwaggerType.Boolean)]
		public bool EstDefaut { get; set; }

		/// <summary>
		/// Date de création.
		/// </summary>
		[Required]
		[ApiMember(Description = "Date de création.", DataType = SwaggerType.Date)]
		public DateTime DatCreation { get; set; }

		/// <summary>
		/// Date de dernière modification.
		/// </summary>
		[Required]
		[ApiMember(Description = "Date de dernière modification.", DataType = SwaggerType.Date)]
		public DateTime DatModif { get; set; }

	}
}
