//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[CompositeIndex(true, "CleGenMandat", "CleGenPersonne", "CleGenSociete", "CleGenSecteur", "CleGenService")]
	public partial class GenMandatMandataire : IHasId<int>
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[AutoIncrement]
		[ApiMember(Description = "Clé primaire.", DataType = SwaggerType.Int)]
		public int Id { get; set; }

		[ForeignKey(typeof(GenMandat), OnDelete = "CASCADE")]
		[Required]
		[ApiMember(IsRequired = true, DataType = SwaggerType.Int)]
		public int CleGenMandat { get; set; }

		[References(typeof(GenPersonne))]
		[Required]
		[ApiMember(IsRequired = true, DataType = SwaggerType.Int)]
		public int CleGenPersonne { get; set; }

		[References(typeof(GenSociete))]
		[ApiMember(DataType = SwaggerType.Int)]
		public int? CleGenSociete { get; set; }

		[References(typeof(GenSecteur))]
		[ApiMember(DataType = SwaggerType.Int)]
		public int? CleGenSecteur { get; set; }

		[References(typeof(GenService))]
		[ApiMember(DataType = SwaggerType.Int)]
		public int? CleGenService { get; set; }

		[Required]
		[ApiMember(IsRequired = true, DataType = SwaggerType.Boolean)]
		public bool EstSuspendu { get; set; }

	}
}
