//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	public partial class GenPersonneSignature
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[ForeignKey(typeof(GenPersonne), OnDelete = "CASCADE")]
		[Required]
		[PrimaryKey]
		[ApiMember(Description = "Clé primaire.", IsRequired = true, DataType = SwaggerType.Int)]
		public int CleGenPersonne { get; set; }

		[Required]
		[ApiMember(IsRequired = true, DataType = "file")]
		public byte[] ImgSignature { get; set; }

		[StringLength(255)]
		[Required]
		[ApiMember(IsRequired = true, DataType = SwaggerType.String)]
		public string TypMime { get; set; }

	}
}
