//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using Tmpi.Pyrene.Infrastructure.Types;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	public partial class GenPersonneSignature : IHasId<int>
	{
        [Alias("CleGenPersonne")]
		[ForeignKey(typeof(GenPersonne), OnDelete = "CASCADE")]
		[Required]
		public int Id { get; set; }

		[Required]
		public byte[] ImgSignature { get; set; }

		[StringLength(255)]
		[Required]
		public string TypMime { get; set; }

	}
}
