//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	public partial class GenPersonneSignature
	{
		/// <summary>
		/// Clé primaire.
		/// </summary>
		[ForeignKey(typeof(GenPersonne), OnDelete = "CASCADE")]
		[Required]
		[PrimaryKey]
		[ApiMember(Description = "Clé primaire.", DataType = SwaggerDataTypes.Integer, Verb = HttpVerbs.Put, IsRequired = true, ParameterType = SwaggerParameterTypes.Path)]
		[ApiMember(Description = "Clé primaire.", DataType = SwaggerDataTypes.Integer, Verb = HttpVerbs.Post, ParameterType = SwaggerParameterTypes.Form)]
		public int CleGenPersonne { get; set; }

		/// <summary>
		/// Image de la signature.
		/// </summary>
		[Required]
		[ApiMember(Description = "Image de la signature.", DataType = SwaggerDataTypes.File, IsRequired = true)]
		public byte[] ImgSignature { get; set; }

		/// <summary>
		/// Type MIME de l'image.
		/// </summary>
		[StringLength(255)]
		[Required]
		[ApiMember(Description = "Type MIME de l'image.", DataType = SwaggerDataTypes.String, IsRequired = true)]
		public string TypMime { get; set; }

	}
}
