//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using Tmpi.Pyrene.Infrastructure.Types;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	public partial class GenTVA : IHasId<int>,
		IAuditable,
		IHasStandard
	{
		[AutoIncrement]
		public int Id { get; set; }

		[StringLength(100)]
		[Required]
		[Index(true)]
		public string CodObjet { get; set; }

		[StringLength(200)]
		[Required]
		[Index]
		public string LibObjet { get; set; }

		[StringLength(500)]
		public string TxtObjet { get; set; }

		[Required]
		public bool EstActif { get; set; }

		[Required]
		public DateTime DatCreation { get; set; }

		[Required]
		public DateTime DatModif { get; set; }

		[StringLength(100)]
		public string CodExterne { get; set; }

		[DecimalLength(5, 2)]
		[Required]
		public decimal TauTVA { get; set; }

	}
}
