CREATE TABLE [SA_TMPI].[Lmp_PrlPreleveur] (
    [ClePreleveur]         SMALLINT         IDENTITY (1, 1) NOT NULL,
    [CleOrgPreleveur]      INT              NULL,
    [CodPreleveur]         VARCHAR (50)     NOT NULL,
    [NomPreleveur]         VARCHAR (100)    NOT NULL,
    [EstActif]             BIT              CONSTRAINT [DF_Lmp_PrlPreleveur_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]          SMALLDATETIME    CONSTRAINT [DF_Lmp_PrlPreleveur_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]          SMALLINT         CONSTRAINT [DF_Lmp_PrlPreleveur_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]             SMALLDATETIME    NULL,
    [CleOperateur]         SMALLINT         NULL,
    [DatValidation]        SMALLDATETIME    NULL,
    [CleValideur]          SMALLINT         NULL,
    [CleExterne]           INT              NULL,
    [CleOrigine]           INT              NULL,
    [AdrCommune_D]         VARCHAR (100)    NULL,
    [NumInsee_D]           VARCHAR (25)     NULL,
    [AdrLongitude_D]       DECIMAL (20, 13) NULL,
    [AdrLatitude_D]        DECIMAL (20, 13) NULL,
    [AdrCommune_A]         VARCHAR (100)    NULL,
    [NumInsee_A]           VARCHAR (25)     NULL,
    [AdrLongitude_A]       DECIMAL (20, 13) NULL,
    [AdrLatitude_A]        DECIMAL (20, 13) NULL,
    [AbvPreleveur]         VARCHAR (25)     NULL,
    [AdrMail]              VARCHAR (100)    NULL,
    [ClePersonne]          SMALLINT         NOT NULL,
    [NumTelephonePortable] VARCHAR (25)     NULL,
    [CleSecteur]           SMALLINT         NULL,
    [EstSynchroOptiTime]   BIT              NULL,
    [CodPostal_D]          VARCHAR (10)     NULL,
    [CodPostal_A]          VARCHAR (10)     NULL,
    [EstEnReserve]         BIT              CONSTRAINT [DF_Lmp_PrlPreleveur_EstEnReserve] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Lmp_PrlPreleveur] PRIMARY KEY CLUSTERED ([ClePreleveur] ASC)
);

