CREATE TABLE [SA_TMPI].[Lms_DosDossier] (
    [CleClasse]          SMALLINT       NULL,
    [CleDossier]         INT            IDENTITY (1, 1) NOT NULL,
    [NumDossier]         VARCHAR (25)   NULL,
    [TxtDossier]         VARCHAR (500)  NULL,
    [CleMotif]           SMALLINT       NULL,
    [CleDevis]           INT            NULL,
    [ClePrescripteur]    INT            NULL,
    [CleClient]          INT            NULL,
    [ClePayeur]          INT            NULL,
    [CleOrgPreleveur]    INT            NULL,
    [CleLaboratoire]     INT            NULL,
    [NivTraitement]      TINYINT        CONSTRAINT [DF_Lms_DosDossier_NivTraitement] DEFAULT ((0)) NOT NULL,
    [DatCreation]        SMALLDATETIME  CONSTRAINT [DF_Lms_DosDossier_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]        SMALLINT       NOT NULL,
    [DatModif]           SMALLDATETIME  NULL,
    [CleOperateur]       SMALLINT       NULL,
    [DatValidation]      SMALLDATETIME  NULL,
    [CleValideur]        SMALLINT       NULL,
    [NbrEchantillon]     SMALLINT       CONSTRAINT [DF_Lms_DosDossier_NbrEchantillon] DEFAULT ((1)) NOT NULL,
    [DatRefFacturation]  SMALLDATETIME  CONSTRAINT [DF_Lms_DosDossier_DatRefFacturation] DEFAULT (getdate()) NULL,
    [CleMNumero_D]       SMALLINT       NOT NULL,
    [CleMNumero_E]       SMALLINT       NOT NULL,
    [CleDossier_Source]  INT            NULL,
    [CleDossier_Cible]   INT            NULL,
    [NumRevision]        TINYINT        NULL,
    [DatRevision]        SMALLDATETIME  NULL,
    [CleReviseur]        INT            NULL,
    [CleDemande]         INT            NULL,
    [EstImpressionAuto]  BIT            CONSTRAINT [DF_Lms_DosDossier_EstImpressionAuto] DEFAULT ((1)) NOT NULL,
    [EstFacturationAuto] BIT            CONSTRAINT [DF_Lms_DosDossier_EstFacturationAuto] DEFAULT ((1)) NOT NULL,
    [CleSecteur]         SMALLINT       NULL,
    [CleService]         SMALLINT       NULL,
    [TypEcheanceFact]    TINYINT        CONSTRAINT [DF_Lms_DosDossier_TypEcheanceFact] DEFAULT ((0)) NOT NULL,
    [DelPaiement]        TINYINT        CONSTRAINT [DF_Lms_DosDossier_DelPaiement] DEFAULT ((0)) NOT NULL,
    [TypEcheancePaiem]   TINYINT        CONSTRAINT [DF_Lms_DosDossier_TypEcheancePaiem] DEFAULT ((0)) NOT NULL,
    [TauTVAReference]    DECIMAL (5, 2) CONSTRAINT [DF_Lms_DosDossier_TauTVAReference] DEFAULT ((0)) NULL,
    [TauRemiseGlobal]    DECIMAL (5, 2) CONSTRAINT [DF_Lms_DosDossier_TauRemiseGlobal] DEFAULT ((0)) NOT NULL,
    [CleTarifReference]  SMALLINT       NULL,
    [CleTarifMetier]     SMALLINT       NULL,
    [CleTarifPayeur]     SMALLINT       NULL,
    [DatEcheance]        SMALLDATETIME  NULL,
    [DatFacturation]     SMALLDATETIME  NULL,
    [CleFacture]         INT            NULL,
    [CleFeuille]         INT            NULL,
    [DatPrelevement]     SMALLDATETIME  NULL,
    [DatReception]       SMALLDATETIME  NULL,
    [NivPrelevement]     VARCHAR (1)    NULL,
    [CleAtelier]         INT            NULL,
    [NumDemande]         VARCHAR (50)   NULL,
    [CleProduit]         SMALLINT       NULL,
    [TypInterpretation]  SMALLINT       NULL,
    [TypValidation]      SMALLINT       NULL,
    [EstAccredite]       BIT            CONSTRAINT [DF_Lms_DosDossierEstAccredite] DEFAULT ((0)) NOT NULL,
    [EstFacturable]      BIT            CONSTRAINT [DF_Lms_DosDossierEstFacturable] DEFAULT ((0)) NOT NULL,
    [EstPaye]            BIT            CONSTRAINT [DF_Lms_DosDossierEstPaye] DEFAULT ((0)) NOT NULL,
    [CleEtablissement]   INT            NULL,
    [TypIdentPP]         TINYINT        NULL,
    [NumPointP]          VARCHAR (50)   NULL,
    [NomPointP]          VARCHAR (100)  NULL,
    [TypIdentPS]         TINYINT        NULL,
    [NumPointS]          VARCHAR (50)   NULL,
    [NomPointS]          VARCHAR (100)  NULL,
    CONSTRAINT [PK_Lms_DosDossier] PRIMARY KEY CLUSTERED ([CleDossier] ASC),
    CONSTRAINT [FK1_Lms_DosDossier] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK10_Lms_DosDossier] FOREIGN KEY ([CleMNumero_E]) REFERENCES [SA_TMPI].[Gen_Cpt_MNumero] ([CleMNumero]),
    CONSTRAINT [FK2_Lms_DosDossier] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [FK3_Lms_DosDossier] FOREIGN KEY ([CleMotif]) REFERENCES [SA_TMPI].[Lmp_MotMotif] ([CleMotif]),
    CONSTRAINT [FK4_Lms_DosDossier] FOREIGN KEY ([ClePrescripteur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK5_Lms_DosDossier] FOREIGN KEY ([CleClient]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK6_Lms_DosDossier] FOREIGN KEY ([ClePayeur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK7_Lms_DosDossier] FOREIGN KEY ([CleOrgPreleveur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK8_Lms_DosDossier] FOREIGN KEY ([CleLaboratoire]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK9_Lms_DosDossier] FOREIGN KEY ([CleMNumero_D]) REFERENCES [SA_TMPI].[Gen_Cpt_MNumero] ([CleMNumero])
);


GO
CREATE NONCLUSTERED INDEX [ID1_Lms_DosDossier]
    ON [SA_TMPI].[Lms_DosDossier]([NumDossier] ASC);

