CREATE TABLE [SA_TMPI].[Lms_DemEchantillon] (
    [CleDemEchantillon]  INT           IDENTITY (1, 1) NOT NULL,
    [CleDemande]         INT           NOT NULL,
    [CleDemPrelevement]  INT           NULL,
    [NumOrdre]           SMALLINT      NOT NULL,
    [NumEchantillon]     VARCHAR (100) NULL,
    [NumEchantillon_Ext] VARCHAR (100) NULL,
    [TxtEchantillon]     VARCHAR (255) NULL,
    [NbrEchantillon]     SMALLINT      NOT NULL,
    [NumEtiquette]       VARCHAR (50)  NULL,
    [NumLot]             SMALLINT      NULL,
    [NumPointP]          VARCHAR (50)  NULL,
    [NomPointP]          VARCHAR (100) NULL,
    [NumPointS]          VARCHAR (50)  NULL,
    [NomPointS]          VARCHAR (100) NULL,
    [ClePreleveur]       INT           NULL,
    [DatPrelevement]     SMALLDATETIME NULL,
    [CleMatrice]         SMALLINT      NULL,
    [NivTraitement]      TINYINT       CONSTRAINT [DF_Lms_DemEchantillon_NivTraitement] DEFAULT ((0)) NOT NULL,
    [CleDosEchantillon]  INT           NULL,
    [CleOrigine]         TINYINT       NULL,
    [CleExterne]         INT           NULL,
    [TypIdentPP]         TINYINT       NULL,
    [TypIdentPS]         TINYINT       NULL,
    CONSTRAINT [PK_Lms_DemEchantillon] PRIMARY KEY CLUSTERED ([CleDemEchantillon] ASC),
    CONSTRAINT [FK1_Lms_DemEchantillon] FOREIGN KEY ([CleDemande]) REFERENCES [SA_TMPI].[Lms_DemDemande] ([CleDemande]),
    CONSTRAINT [FK2_Lms_DemEchantillon] FOREIGN KEY ([CleDemPrelevement]) REFERENCES [SA_TMPI].[Lms_DemPrelevement] ([CleDemPrelevement]),
    CONSTRAINT [FK3_Lms_DemEchantillon] FOREIGN KEY ([CleMatrice]) REFERENCES [SA_TMPI].[Lmp_MatMatrice] ([CleMatrice]),
    CONSTRAINT [UN_Lms_DemEchantillon] UNIQUE NONCLUSTERED ([CleDemande] ASC, [NumOrdre] ASC)
);

