CREATE TABLE [SA_TMPI].[Sdr9_DemDemande] (
    [CleDemande]            INT            NOT NULL,
    [CleDemandeLims]        INT            NULL,
    [CodDemande]            VARCHAR (100)  NOT NULL,
    [CodDemandePrestataire] VARCHAR (100)  NULL,
    [TypDemande]            VARCHAR (1)    NULL,
    [DatDemande]            SMALLDATETIME  NULL,
    [LibDemande]            VARCHAR (255)  NULL,
    [DatDebut]              SMALLDATETIME  NULL,
    [DatFin]                SMALLDATETIME  NULL,
    [RefMarche]             VARCHAR (50)   NULL,
    [TxtCommanditaire]      VARCHAR (2000) NULL,
    [CleCommanditaire]      SMALLINT       NULL,
    [CleCommanditaireT]     SMALLINT       NULL,
    [ClePrestataire]        SMALLINT       NULL,
    [ClePrestataireT]       SMALLINT       NULL,
    [ClePayeur]             SMALLINT       NULL,
    [ClePayeurT]            SMALLINT       NULL,
    [NivErreur]             TINYINT        NULL,
    [VerScenario]           VARCHAR (10)   NULL,
    [NomScenario]           VARCHAR (150)  NULL,
    [DatCreation]           SMALLDATETIME  NULL,
    [RefFichierEnvoye]      VARCHAR (2000) NULL,
    [CleEmetteur]           SMALLINT       NULL,
    [CleEmetteurT]          SMALLINT       NULL,
    [CleDestinataire]       SMALLINT       NULL,
    [CleDestinataireT]      SMALLINT       NULL,
    [CodScenario]           VARCHAR (10)   NULL,
    [NomFichier]            VARCHAR (255)  NULL,
    [CleSI]                 INT            NOT NULL,
    CONSTRAINT [PK_Sdr9_DemDemande] PRIMARY KEY CLUSTERED ([CleDemande] ASC),
    CONSTRAINT [UN_Sdr9_DemDemande] UNIQUE NONCLUSTERED ([CleDemande] ASC, [CodDemande] ASC)
);

