CREATE TABLE [SA_TMPI].[t_Engage] (
    [CleExercice]   TINYINT         NOT NULL,
    [CleEngage]     INT             IDENTITY (1, 1) NOT NULL,
    [NumEngage]     VARCHAR (25)    NULL,
    [TypEngage]     TINYINT         CONSTRAINT [DF_t_Engage_TypEngage] DEFAULT ((0)) NOT NULL,
    [DatEngage]     DATETIME        CONSTRAINT [DF_t_Engage_DatEngage] DEFAULT (getdate()) NOT NULL,
    [CleFourn]      SMALLINT        NOT NULL,
    [CleClient]     SMALLINT        NOT NULL,
    [CleBudget]     SMALLINT        NOT NULL,
    [CleImput]      SMALLINT        NULL,
    [CleDevise]     TINYINT         NULL,
    [MntPrevu]      DECIMAL (15, 2) CONSTRAINT [DF_t_Engage_MntPrevu] DEFAULT ((0)) NOT NULL,
    [MntRealise]    DECIMAL (15, 2) CONSTRAINT [DF_t_Engage_MntRealise] DEFAULT ((0)) NOT NULL,
    [MntHT]         DECIMAL (15, 2) CONSTRAINT [DF_t_Engage_MntHT] DEFAULT ((0)) NOT NULL,
    [MntTva]        DECIMAL (15, 2) CONSTRAINT [DF_t_Engage_MntTva] DEFAULT ((0)) NOT NULL,
    [TauRecup]      DECIMAL (5, 2)  CONSTRAINT [DF_t_Engage_TauRecup] DEFAULT ((0)) NOT NULL,
    [CleObjet]      INT             NULL,
    [LibFourn]      VARCHAR (100)   NULL,
    [NomDemandeur]  VARCHAR (50)    NOT NULL,
    [CleValideur_1] SMALLINT        NULL,
    [CleValideur_2] SMALLINT        NULL,
    [NivSaisie]     TINYINT         CONSTRAINT [DF_t_Engage_NivSaisie] DEFAULT ((0)) NOT NULL,
    [DatValidation] DATETIME        NULL,
    [CleNomenc]     SMALLINT        NULL,
    [CleMotif]      SMALLINT        NULL,
    [LibEngage]     VARCHAR (100)   NULL,
    [TauTVA]        DECIMAL (5, 2)  NULL,
    [TxtEngage]     VARCHAR (255)   NULL,
    [DatCaducite]   DATETIME        NULL,
    [IndManuelle]   DECIMAL (1)     NULL,
    [CleNature]     SMALLINT        NULL,
    [MntFacture]    DECIMAL (15, 2) NULL,
    CONSTRAINT [PK_t_Engage] PRIMARY KEY CLUSTERED ([CleEngage] ASC)
);

