CREATE TABLE [SA_TMPI].[t_Interv] (
    [CleExercice]     SMALLINT        NOT NULL,
    [CleEquip]        INT             NOT NULL,
    [CleInterv]       INT             IDENTITY (1, 1) NOT NULL,
    [NumInterv]       VARCHAR (25)    NOT NULL,
    [CleFamille]      SMALLINT        NULL,
    [CleFourn]        SMALLINT        NOT NULL,
    [CleClient]       SMALLINT        NOT NULL,
    [CleImput]        SMALLINT        NULL,
    [CleDevise]       TINYINT         NULL,
    [MntHT]           DECIMAL (15, 2) CONSTRAINT [DF_t_Interv_MntHT] DEFAULT ((0)) NOT NULL,
    [MntTVA]          DECIMAL (15, 2) CONSTRAINT [DF_t_Interv_MntTVA] DEFAULT ((0)) NOT NULL,
    [NomDemandeur]    VARCHAR (50)    NOT NULL,
    [DatDemande]      DATETIME        NOT NULL,
    [DatPrevue]       DATETIME        NOT NULL,
    [DatInterv]       DATETIME        NULL,
    [DatSaisie]       DATETIME        NULL,
    [TxtMotif]        VARCHAR (255)   NULL,
    [TxtInterv]       VARCHAR (2000)  NULL,
    [NivUrgence]      TINYINT         CONSTRAINT [DF_t_Interv_NivUrgence] DEFAULT ((0)) NOT NULL,
    [TxtDemande]      VARCHAR (255)   NULL,
    [LstAcces]        VARCHAR (255)   NULL,
    [CleRespon]       SMALLINT        NULL,
    [CleEquipPlanif]  INT             NULL,
    [DatValidation]   DATETIME        NULL,
    [CleValideur]     SMALLINT        NULL,
    [NivSaisie]       TINYINT         CONSTRAINT [DF_t_Interv_NivSaisie] DEFAULT ((0)) NOT NULL,
    [CleEquipMInterv] INT             NULL,
    [CleContrat]      SMALLINT        NULL,
    [CleDocument1]    SMALLINT        NULL,
    [CleDocument2]    SMALLINT        NULL,
    CONSTRAINT [PK_Interv] PRIMARY KEY CLUSTERED ([CleInterv] ASC),
    CONSTRAINT [FK1_t_Interv] FOREIGN KEY ([CleEquip]) REFERENCES [SA_TMPI].[t_Equip] ([CleEquip]),
    CONSTRAINT [FK2_t_Interv] FOREIGN KEY ([CleFamille]) REFERENCES [SA_TMPI].[t_IFamille] ([CleIFamille]),
    CONSTRAINT [FK3_t_Interv] FOREIGN KEY ([CleExercice]) REFERENCES [SA_TMPI].[Gen_DivExercice] ([CleExercice]),
    CONSTRAINT [FK4_t_Interv] FOREIGN KEY ([CleClient]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN_t_Interv] UNIQUE NONCLUSTERED ([NumInterv] ASC)
);

