CREATE TABLE [SA_TMPI].[t_Magasin] (
    [CleMagasin]          SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CodMagasin]          VARCHAR (50)  NOT NULL,
    [LibMagasin]          VARCHAR (100) NOT NULL,
    [TxtMagasin]          VARCHAR (255) NULL,
    [CleService]          SMALLINT      NOT NULL,
    [DatSaisie]           DATETIME      CONSTRAINT [DF_t_Magasin_DatSaisie] DEFAULT (getdate()) NULL,
    [CleOperateur]        SMALLINT      CONSTRAINT [DF_t_Magasin_CleOperateur] DEFAULT ((0)) NULL,
    [NumVersion]          TINYINT       CONSTRAINT [DF_t_Magasin_NumVersion] DEFAULT ((0)) NULL,
    [DatValidation]       DATETIME      NULL,
    [CleValideur]         SMALLINT      NULL,
    [AdrRue]              VARCHAR (255) NULL,
    [AdrCode]             VARCHAR (25)  NULL,
    [AdrVille]            VARCHAR (100) NULL,
    [NumTelep]            VARCHAR (25)  NULL,
    [NumTelec]            VARCHAR (25)  NULL,
    [NumEMail]            VARCHAR (100) NULL,
    [CleEtatU_BonCde]     SMALLINT      NULL,
    [CleEtatU_Etiquette]  SMALLINT      NULL,
    [EstEcoAutorise]      BIT           CONSTRAINT [DF_t_Magasin_EstEcoAutorise] DEFAULT ((1)) NOT NULL,
    [CleMagasinFourn]     SMALLINT      NULL,
    [CleMNumero_C]        SMALLINT      NULL,
    [CleMNumero_D]        SMALLINT      NULL,
    [CleEtatU_Etiquette2] INT           NULL,
    CONSTRAINT [PK_t_Magasin] PRIMARY KEY CLUSTERED ([CleMagasin] ASC),
    CONSTRAINT [FK1_t_Magasin] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN1_t_Magasin] UNIQUE NONCLUSTERED ([CodMagasin] ASC),
    CONSTRAINT [UN2_CleService] UNIQUE NONCLUSTERED ([CleService] ASC)
);

