//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.ServiceModel.Types;

namespace Tmpi.Pyrene.ServiceModel
{
	/// <summary>
	/// Autocomplete une entité <see cref="GenCompteur" />.
	/// </summary>
	[Route("/GenCompteur/Autocomplete", "GET", Summary = "Autocomplete une entité GenCompteur.")]
	public partial class AutocompleteGenCompteur : AutocompleteRequestBase
	{
	}
}
