// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Tmpi.Pyrene.ServiceModel.Types
{
    public partial class GenCompteur : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string CodObjet { get; set;}
        [Required]
        public string LibObjet { get; set;}
        public string TxtObjet { get; set;}
        [Required]
        public bool EstActif { get; set;}
        [Required]
        public DateTime DatCreation { get; set;}
        [Required]
        public DateTime DatModif { get; set;}
        public string CodExterne { get; set;}
        [Required]
        public TypCompteur TypCompteur { get; set;}
         [References(typeof(GenSociete))]          
        public int? CleGenSociete { get; set;}
         [References(typeof(GenSecteur))]          
        public int? CleGenSecteur { get; set;}
         [References(typeof(GenService))]          
        public int? CleGenService { get; set;}
        [Required]
        public TypPeriodicite TypPeriodicite { get; set;}
        public string ValPrefixe1 { get; set;}
        public string ValFormatDate1 { get; set;}
        public string ValPrefixe2 { get; set;}
        [Required]
        public byte NbrDigit { get; set;}
        public string ValSuffixe1 { get; set;}
        public string ValFormatDate2 { get; set;}
        public string ValSuffixe2 { get; set;}
        public string LstFormatMois { get; set;}
    }

}
#pragma warning restore 1591
