// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Tmpi.Pyrene.ServiceModel.Types
{
    public partial class GenFournContact 
    {
        [AutoIncrement]
		[PrimaryKey]
        public int CleContact { get; set;}
         [References(typeof(GenFourn))]          
        [Required]
        public int CleFourn { get; set;}
        [Required]
        public string NomContact { get; set;}
        public string PreContact { get; set;}
        public string TxtContact { get; set;}
        public string NumTelep { get; set;}
        public string NumFax { get; set;}
        public string NumEmail { get; set;}
        public TypGenre? TypGenre { get; set;}
        public string CodFonction { get; set;}
    }

}
#pragma warning restore 1591
