//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.ServiceModel.Types;

namespace Tmpi.Pyrene.ServiceModel
{
	/// <summary>
	/// Retourne une entité <see cref="GenPersonneProfil" /> à partir de son Id.
	/// </summary>
	[Route("/GenPersonneProfil/{Id}", "GET", Summary = "Retourne une entité GenPersonneProfil à partir de son Id.")]
	public partial class GetGenPersonneProfil : GetByIdRequestBase<GenPersonneProfil>
	{
	}
}
