//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.ServiceModel.Types
{
	[Schema("Gen")]
	[CompositeIndex(true, nameof(CleMandat), nameof(ClePersonne), nameof(CleService))]
	[Route("/Mandat/{CleMandat}/Mandataire", HttpVerbs.Post, Summary = "Ajoute ou remplace une entité MandatMandataire à partir de son id", Notes = SwaggerDescriptions.UpsertRequestNotes)]
	[ApiResponse(HttpStatusCode.Conflict, "L'entité MandatMandataire spécifiée est un doublon")]
	[ApiResponse(HttpStatusCode.NotFound, "L'entité MandatMandataire spécifiée est introuvable")]
	public partial class MandatMandataire : IReturn<MandatMandataire>, IPost, IAuditable
	{
		/// <summary>
		/// Identifiant unique (immutable).
		/// </summary>
		/// <remarks>
		/// Clé primaire auto-incrémentée.
		/// </remarks>
		[AutoIncrement]
		[PrimaryKey]
		[ApiMember(Description = "Identifiant unique (immutable)", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int CleMandataire { get; set; }

		/// <summary>
		/// Identifiant unique du mandat parent.
		/// </summary>
		/// <remarks>
		/// Référence <see cref="Mandat.CleMandat"/>.
		/// </remarks>
		[ForeignKey(typeof(Mandat), OnDelete = "CASCADE")]
		[Required]
		[ApiMember(Description = "Identifiant unique du mandat parent", DataType = SwaggerDataTypes.Int, IsRequired = true, ParameterType = SwaggerParamTypes.Path)]
		public int CleMandat { get; set; }

		/// <summary>
		/// Entité référencée par <see cref="CleMandat"/>.
		/// </summary>
		[Reference]
		public Mandat Mandat { get; set; }

		/// <summary>
		/// Identifiant unique de l'utilisateur mandataire.
		/// </summary>
		/// <remarks>
		/// Référence <see cref="Personne.ClePersonne"/>.
		/// </remarks>
		[References(typeof(Personne))]
		[Required]
		[ApiMember(Description = "Identifiant unique de l'utilisateur mandataire", DataType = SwaggerDataTypes.Int, IsRequired = true)]
		public int ClePersonne { get; set; }

		/// <summary>
		/// Entité référencée par <see cref="ClePersonne"/>.
		/// </summary>
		[Reference]
		public Personne Personne { get; set; }

		/// <summary>
		/// Identifiant unique du service ayant accès au mandat, ou null pour tous les services.
		/// </summary>
		/// <remarks>
		/// Référence <see cref="Service.CleService"/>.
		/// </remarks>
		[References(typeof(Service))]
		[ApiMember(Description = "Identifiant unique du service ayant accès au mandat, ou null pour tous les services", DataType = SwaggerDataTypes.Int)]
		public int? CleService { get; set; }

		/// <summary>
		/// Entité référencée par <see cref="CleService"/>.
		/// </summary>
		[Reference]
		public Service Service { get; set; }

		/// <summary>
		/// Si true, le mandat est suspendu.
		/// </summary>
		[Required]
		[ApiMember(Description = "Si true, le mandat est suspendu", DataType = SwaggerDataTypes.Bool, IsRequired = true)]
		public bool EstSuspendu { get; set; }

		/// <summary>
		/// Date de création (immutable).
		/// </summary>
		[Required]
		public DateTime DatCreation { get; set; }

		/// <summary>
		/// Identifiant unique de l'utilisateur responsable de la création (immutable).
		/// </summary>
		[Required]
		public int CleCreateur { get; set; }

		/// <summary>
		/// Date de dernière modification (immutable).
		/// </summary>
		public DateTime? DatEdition { get; set; }

		/// <summary>
		/// Identifiant unique de l'utilisateur responsable de la dernière modification (immutable).
		/// </summary>
		public int? CleEditeur { get; set; }

	}
}
