//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

import { Component, OnInit } from '@angular/core';

import { PagedData } from './paged-data';
import { ServiceService } from './service.service';
import { Service } from './dtos';

@Component({
	selector: 'service-list',
	templateUrl: 'service-list.component.html',
	providers: [ServiceService]
})
export class ServiceListComponent implements OnInit {
	service: PagedData<Service> = {
		sort: 'LibService',
		pageIndex: 0,
		pageSize: 20
	}

	constructor(private serviceService: ServiceService) {
	}

	ngOnInit() {
		this.loadService();
	}

	loadService(): void {
		const fields = 'CodService,LibService,EstActif';
		const skip = this.service.pageIndex * this.service.pageSize;
		this.serviceService.selectService(fields, [this.service.sort], skip, this.service.pageSize)
			.then(r => this.service.data = r.Results);
	}

	deleteService(id: number): void {
		this.serviceService.deleteService(id);
	}
}
