CREATE TABLE [SA_TMPI].[Edi_DemDemande] (
    [CleEdiDemande]       INT           IDENTITY (1, 1) NOT NULL,
    [CleSI]               INT           NOT NULL,
    [TypReferentiel]      TINYINT       NOT NULL,
    [NumDemande]          VARCHAR (100) NOT NULL,
    [DatDemande]          SMALLDATETIME NULL,
    [DatIntervention]     SMALLDATETIME NULL,
    [DatDebut]            SMALLDATETIME NULL,
    [DatFin]              SMALLDATETIME NULL,
    [TxtDemande]          VARCHAR (255) NULL,
    [CleClient]           INT           NULL,
    [CleClient_Ref]       INT           NOT NULL,
    [CleOrgPreleveur]     INT           NULL,
    [CleOrgPreleveur_Ref] INT           NOT NULL,
    [CleAtelier]          INT           NULL,
    [CleAtelier_Ref]      INT           NULL,
    [CleMotif]            INT           NULL,
    [CleMotif_Ref]        INT           NULL,
    [CleEmetteur]         INT           NULL,
    [CleEmetteur_Ref]     INT           NOT NULL,
    [CleDestinataire]     INT           NULL,
    [CleDestinataire_Ref] INT           NOT NULL,
    [NomFichier]          VARCHAR (255) NULL,
    [DatCreation]         SMALLDATETIME NOT NULL,
    [CleCreateur]         SMALLINT      NOT NULL,
    [NivErreur]           TINYINT       NOT NULL,
    CONSTRAINT [PK_Edi_DemDemande] PRIMARY KEY CLUSTERED ([CleEdiDemande] ASC),
    CONSTRAINT [UN_Edi_DemDemande] UNIQUE NONCLUSTERED ([TypReferentiel] ASC, [NumDemande] ASC)
);

