CREATE TABLE [SA_TMPI].[Lmp_ForFormule] (
    [CodReferentiel]  VARCHAR (50)  NOT NULL,
    [CleParametre]    SMALLINT      NULL,
    [CleFormule]      SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CleFormule_C]    SMALLINT      NULL,
    [CleFormule_H]    SMALLINT      NOT NULL,
    [CodFormule]      VARCHAR (50)  NOT NULL,
    [LibFormule]      VARCHAR (200) NOT NULL,
    [DomFormule]      VARCHAR (255) NULL,
    [NumFormule]      VARCHAR (25)  NULL,
    [RefFormule]      VARCHAR (100) NULL,
    [NumPage]         VARCHAR (15)  NULL,
    [CodParametreG]   VARCHAR (20)  NULL,
    [NumOrdre]        VARCHAR (5)   NULL,
    [NivFormule]      TINYINT       NULL,
    [TxtFormule]      VARCHAR (500) NULL,
    [TxtFormuleC]     VARCHAR (500) NULL,
    [TxtCondition]    VARCHAR (500) NULL,
    [TxtConditionC]   VARCHAR (500) NULL,
    [ValCondition_00] VARCHAR (50)  NULL,
    [ValCondition_01] VARCHAR (50)  NULL,
    [ValCondition_02] VARCHAR (50)  NULL,
    [ValCondition_03] VARCHAR (50)  NULL,
    [ValCondition_04] VARCHAR (50)  NULL,
    [ValCondition_05] VARCHAR (50)  NULL,
    [ValCondition_06] VARCHAR (50)  NULL,
    [ValCondition_07] VARCHAR (50)  NULL,
    [ValCondition_08] VARCHAR (50)  NULL,
    [ValCondition_09] VARCHAR (50)  NULL,
    [ValCondition_10] VARCHAR (50)  NULL,
    [ValCondition_11] VARCHAR (50)  NULL,
    [ValCondition_12] VARCHAR (50)  NULL,
    [ValCondition_13] VARCHAR (50)  NULL,
    [ValCondition_14] VARCHAR (50)  NULL,
    [IndMs]           VARCHAR (50)  NULL,
    [IndMm]           VARCHAR (50)  NULL,
    [IndMat]          VARCHAR (50)  NULL,
    [IndCb]           VARCHAR (50)  NULL,
    [IndAmi]          VARCHAR (50)  NULL,
    [IndMg]           VARCHAR (50)  NULL,
    [IndPh]           VARCHAR (50)  NULL,
    [IndDca]          VARCHAR (50)  NULL,
    [IndDcl]          VARCHAR (50)  NULL,
    [IndDcd]          VARCHAR (50)  NULL,
    [IndAut]          VARCHAR (50)  NULL,
    [ValCBo]          VARCHAR (50)  NULL,
    [ValMS]           VARCHAR (50)  NULL,
    [EstACompiler]    BIT           CONSTRAINT [DF_Lmp_ForFormule_EstACompiler] DEFAULT ((1)) NOT NULL,
    [EstActif]        BIT           CONSTRAINT [DF_Lmp_ForFormule_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]     SMALLDATETIME CONSTRAINT [DF_Lmp_ForFormule_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]     SMALLINT      CONSTRAINT [DF_Lmp_ForFormule_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]        SMALLDATETIME NULL,
    [CleOperateur]    SMALLINT      NULL,
    [DatValidation]   SMALLDATETIME NULL,
    [CleValideur]     SMALLINT      NULL,
    [CleExterne]      INT           NULL,
    [CleOrigine]      INT           NULL,
    CONSTRAINT [PK_Lmp_ForFormule] PRIMARY KEY CLUSTERED ([CleFormule] ASC)
);

