CREATE TABLE [SA_TMPI].[Lmp_ComCommemo] (
    [CleSecteur]      SMALLINT       NULL,
    [CleCommemo]      SMALLINT       IDENTITY (1, 1) NOT NULL,
    [CleCommemo_C]    SMALLINT       NULL,
    [CleCommemo_H]    SMALLINT       NULL,
    [TypCommemo]      TINYINT        CONSTRAINT [DF_Lmp_ComCommemo_TypCommemo] DEFAULT ((1)) NOT NULL,
    [CodCommemo]      VARCHAR (50)   NOT NULL,
    [AbvCommemo]      VARCHAR (50)   NULL,
    [LibCommemo]      VARCHAR (200)  NOT NULL,
    [LibCommemo_I]    VARCHAR (200)  NULL,
    [TxtCommemo]      VARCHAR (1000) NULL,
    [NumOrdre]        SMALLINT       CONSTRAINT [DF_Lmp_ComCommemo_NumOrdre] DEFAULT ((999)) NOT NULL,
    [EstObligatoire]  BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstObligatoire] DEFAULT ((0)) NOT NULL,
    [TypDonnee]       TINYINT        CONSTRAINT [DF_Lmp_ComCommemo_TypDonnee] DEFAULT ((1)) NOT NULL,
    [TypSaisie]       TINYINT        CONSTRAINT [DF_Lmp_ComCommemo_TypSaisie] DEFAULT ((0)) NOT NULL,
    [CodTableExterne] VARCHAR (50)   NULL,
    [EstDeTerrain]    BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstDeTerrain] DEFAULT ((0)) NOT NULL,
    [NbrCaractere]    TINYINT        NULL,
    [NbrDecimale]     TINYINT        NULL,
    [NbrSignificatif] TINYINT        NULL,
    [FrmPresentation] VARCHAR (25)   NULL,
    [EstImprimable]   BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstImprimable] DEFAULT ((1)) NOT NULL,
    [EstExportable]   BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstExportable] DEFAULT ((1)) NOT NULL,
    [EstActif]        BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]     SMALLDATETIME  CONSTRAINT [DF_Lmp_ComCommemo_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]     SMALLINT       CONSTRAINT [DF_Lmp_ComCommemo_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]        SMALLDATETIME  NULL,
    [CleOperateur]    SMALLINT       NULL,
    [DatValidation]   SMALLDATETIME  NULL,
    [CleValideur]     SMALLINT       NULL,
    [CleExterne]      INT            NULL,
    [CleOrigine]      INT            NULL,
    [CleUniteT]       SMALLINT       NULL,
    [CleService]      SMALLINT       NULL,
    [EstFacturable]   BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstFacturable] DEFAULT ((0)) NOT NULL,
    [EstQteFacturee]  BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstQteFacturee] DEFAULT ((0)) NOT NULL,
    [CleFamille]      SMALLINT       NULL,
    [PosCommemo]      VARCHAR (1)    NULL,
    [TypTMPI]         TINYINT        NULL,
    [EstPrxFacture]   BIT            CONSTRAINT [DF_Lmp_ComCommemo_EstPrxFacture] DEFAULT ((0)) NOT NULL,
    [EstAccredite]    BIT            CONSTRAINT [DF_Lmp_ComCommemoEstAccredite] DEFAULT ((0)) NOT NULL,
    [CleLaboratoire]  INT            NULL,
    [CleParametre]    INT            NULL,
    [CleEtape]        TINYINT        NULL,
    CONSTRAINT [PK_Lmp_ComCommemo] PRIMARY KEY CLUSTERED ([CleCommemo] ASC),
    CONSTRAINT [FK_Lmp_ComCommemo_CleParametre] FOREIGN KEY ([CleParametre]) REFERENCES [SA_TMPI].[Lmp_ParParametre] ([CleParametre]),
    CONSTRAINT [FK1_Lmp_ComCommemo] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK2_Lmp_ComCommemo] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN_Lmp_ComCommemo] UNIQUE NONCLUSTERED ([CodCommemo] ASC, [TypCommemo] ASC)
);

