CREATE TABLE [SA_TMPI].[Lmp_GrpCommemo] (
    [CleGroupeP]     SMALLINT    NOT NULL,
    [CleGrpCommemo]  SMALLINT    IDENTITY (1, 1) NOT NULL,
    [CleUniteT]      SMALLINT    NULL,
    [NumOrdre]       SMALLINT    CONSTRAINT [DF_Lmp_GrpCommemo_NumOrdre] DEFAULT ((0)) NOT NULL,
    [EstOptionnel]   BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstOptionnel] DEFAULT ((0)) NOT NULL,
    [EstObligatoire] BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstObligatoire] DEFAULT ((0)) NOT NULL,
    [EstAccredite]   BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstAccredite] DEFAULT ((0)) NOT NULL,
    [EstImprimable]  BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstImprimable] DEFAULT ((1)) NOT NULL,
    [EstExportable]  BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstExportable] DEFAULT ((1)) NOT NULL,
    [EstFacturable]  BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstFacturable] DEFAULT ((1)) NOT NULL,
    [CleExterne]     INT         NULL,
    [CleOrigine]     TINYINT     NULL,
    [CleLaboratoire] INT         NULL,
    [EstHorsForfait] BIT         CONSTRAINT [DF_Lmp_GrpCommemo_EstHorsForfait] DEFAULT ((0)) NOT NULL,
    [EstQteFacturee] BIT         CONSTRAINT [DF_Lmp_GrpCommemoEstQteFacturee] DEFAULT ((0)) NOT NULL,
    [EstPrxFacture]  BIT         CONSTRAINT [DF_Lmp_GrpCommemoEstPrxFacture] DEFAULT ((0)) NOT NULL,
    [CleCommemo]     SMALLINT    NULL,
    [TypUsage]       VARCHAR (1) NULL,
    CONSTRAINT [PK_Lmp_GrpCommemo] PRIMARY KEY CLUSTERED ([CleGrpCommemo] ASC),
    CONSTRAINT [FK1_Lmp_GrpCommemo] FOREIGN KEY ([CleCommemo]) REFERENCES [SA_TMPI].[Lmp_ComCommemo] ([CleCommemo]),
    CONSTRAINT [FK2_Lmp_GrpCommemo] FOREIGN KEY ([CleUniteT]) REFERENCES [SA_TMPI].[Lmp_UniUniteT] ([CleUniteT]),
    CONSTRAINT [FK3_Lmp_GrpCommemo] FOREIGN KEY ([CleLaboratoire]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [UN_Lmp_GrpCommemo] UNIQUE NONCLUSTERED ([CleGroupeP] ASC, [CleCommemo] ASC, [TypUsage] ASC)
);

