CREATE TABLE [SA_TMPI].[Lmp_MetMethode] (
    [CleFamille]    SMALLINT       CONSTRAINT [DF_Lmp_MetMethode_CleFamille] DEFAULT ((0)) NULL,
    [CleMethode]    SMALLINT       IDENTITY (1, 1) NOT NULL,
    [CleMethode_C]  SMALLINT       NULL,
    [CleMethode_H]  SMALLINT       NOT NULL,
    [CodMethode]    NVARCHAR (50)  NOT NULL,
    [LibMethode]    VARCHAR (200)  NOT NULL,
    [TxtMethode]    VARCHAR (2000) NULL,
    [CodReference]  VARCHAR (50)   NULL,
    [TxtReference]  VARCHAR (1000) NULL,
    [EstGenerique]  BIT            CONSTRAINT [DF_Lmp_MetMethode_EstGenerique] DEFAULT ((0)) NOT NULL,
    [CleMethode_G]  SMALLINT       CONSTRAINT [DF_Lmp_MetMethode_CleMethode_G] DEFAULT ((0)) NULL,
    [EstActif]      BIT            CONSTRAINT [DF_Lmp_MetMethode_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]   SMALLDATETIME  CONSTRAINT [DF_Lmp_MetMethode_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]   SMALLINT       CONSTRAINT [DF_Lmp_MetMethode_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]      SMALLDATETIME  NULL,
    [CleOperateur]  SMALLINT       NULL,
    [DatValidation] SMALLDATETIME  NULL,
    [CleValideur]   SMALLINT       NULL,
    [CleExterne]    INT            NULL,
    [CleOrigine]    SMALLINT       NULL,
    [LibMethode_I]  VARCHAR (200)  NOT NULL,
    [CleSecteur]    SMALLINT       NULL,
    [CleService]    SMALLINT       NULL,
    CONSTRAINT [PK_Lmp_MetMethode] PRIMARY KEY CLUSTERED ([CleMethode] ASC),
    CONSTRAINT [FK1_Lmp_MetMethode] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK2_Lmp_MetMethode] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN_Lmp_MetMethode] UNIQUE NONCLUSTERED ([CleMethode_H] ASC, [CodMethode] ASC)
);

