CREATE TABLE [SA_TMPI].[Lms0_DosDossier] (
    [CleClasse]          SMALLINT       NULL,
    [CleDossier]         INT            IDENTITY (1, 1) NOT NULL,
    [NumDossier]         VARCHAR (25)   NULL,
    [TxtDossier]         VARCHAR (500)  NULL,
    [CleMotif]           SMALLINT       NULL,
    [CleDevis]           INT            NULL,
    [ClePrescripteur]    INT            NULL,
    [CleClient]          INT            NULL,
    [ClePayeur]          INT            NULL,
    [CleOrgPreleveur]    INT            NULL,
    [CleLaboratoire]     INT            NULL,
    [NivTraitement]      TINYINT        CONSTRAINT [DF_Lms0_DosDossier_NivTraitement] DEFAULT ((0)) NOT NULL,
    [DatCreation]        SMALLDATETIME  CONSTRAINT [DF_Lms0_DosDossier_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]        SMALLINT       NOT NULL,
    [DatModif]           SMALLDATETIME  NULL,
    [CleOperateur]       SMALLINT       NULL,
    [DatValidation]      SMALLDATETIME  NULL,
    [CleValideur]        SMALLINT       NULL,
    [NbrEchantillon]     SMALLINT       CONSTRAINT [DF_Lms0_DosDossier_NbrEchantillon] DEFAULT ((1)) NOT NULL,
    [DatRefFacturation]  SMALLDATETIME  CONSTRAINT [DF_Lms0_DosDossier_DatRefFacturation] DEFAULT (getdate()) NULL,
    [CleMNumero_D]       SMALLINT       NOT NULL,
    [CleMNumero_E]       SMALLINT       NOT NULL,
    [CleDossier_Source]  INT            NULL,
    [CleDossier_Cible]   INT            NULL,
    [NumRevision]        TINYINT        CONSTRAINT [DF_Lms0_DosDossier_NumRevision] DEFAULT ((0)) NOT NULL,
    [DatRevision]        SMALLDATETIME  NULL,
    [CleReviseur]        INT            NULL,
    [CleDemande]         INT            NULL,
    [EstImpressionAuto]  BIT            CONSTRAINT [DF_Lms0_DosDossier_EstImpressionAuto] DEFAULT ((1)) NOT NULL,
    [EstFacturationAuto] BIT            CONSTRAINT [DF_Lms0_DosDossier_EstFacturationAuto] DEFAULT ((1)) NOT NULL,
    [CleSecteur]         SMALLINT       NULL,
    [CleService]         SMALLINT       NULL,
    [DelPaiement]        TINYINT        CONSTRAINT [DF_Lms0_DosDossier_DelPaiement] DEFAULT ((0)) NOT NULL,
    [TypEcheanceFact]    TINYINT        CONSTRAINT [DF_Lms0_DosDossier_TypEcheanceFact] DEFAULT ((0)) NOT NULL,
    [TypEcheancePaiem]   TINYINT        CONSTRAINT [DF_Lms0_DosDossier_TypEcheancePaiem] DEFAULT ((0)) NOT NULL,
    [TauRemiseGlobal]    DECIMAL (5, 2) CONSTRAINT [DF_Lms0_DosDossier_TauRemiseGlobal] DEFAULT ((0)) NOT NULL,
    [TauTVAReference]    DECIMAL (5, 2) CONSTRAINT [DF_Lms0_DosDossier_TauTVAReference] DEFAULT ((0)) NULL,
    [CleTarifReference]  SMALLINT       NULL,
    [CleTarifMetier]     SMALLINT       NULL,
    [CleTarifPayeur]     SMALLINT       NULL,
    [DatEcheance]        SMALLDATETIME  NULL,
    [DatFacturation]     SMALLDATETIME  NULL,
    [CleFacture]         INT            NULL,
    [CleFeuille]         INT            NULL,
    [DatPrelevement]     SMALLDATETIME  NULL,
    [DatReception]       SMALLDATETIME  NULL,
    [NivPrelevement]     VARCHAR (1)    NULL,
    [CleAtelier]         INT            NULL,
    [NumDemande]         VARCHAR (50)   NULL,
    [CleProduit]         SMALLINT       NULL,
    CONSTRAINT [PK_Lms0_DosDossier] PRIMARY KEY CLUSTERED ([CleDossier] ASC),
    CONSTRAINT [FK1_Lms0_DosDossier] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK10_Lms0_DosDossier] FOREIGN KEY ([CleMNumero_E]) REFERENCES [SA_TMPI].[Gen_Cpt_MNumero] ([CleMNumero]),
    CONSTRAINT [FK2_Lms0_DosDossier] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [FK3_Lms0_DosDossier] FOREIGN KEY ([CleMotif]) REFERENCES [SA_TMPI].[Lmp_MotMotif] ([CleMotif]),
    CONSTRAINT [FK4_Lms0_DosDossier] FOREIGN KEY ([ClePrescripteur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK5_Lms0_DosDossier] FOREIGN KEY ([CleClient]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK6_Lms0_DosDossier] FOREIGN KEY ([ClePayeur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK7_Lms0_DosDossier] FOREIGN KEY ([CleOrgPreleveur]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK8_Lms0_DosDossier] FOREIGN KEY ([CleLaboratoire]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers]),
    CONSTRAINT [FK9_Lms0_DosDossier] FOREIGN KEY ([CleMNumero_D]) REFERENCES [SA_TMPI].[Gen_Cpt_MNumero] ([CleMNumero])
);

