CREATE TABLE [SA_TMPI].[Lms0_DosParametre] (
    [CleDossier]           INT             NOT NULL,
    [ClePrelevement]       INT             NOT NULL,
    [CleDosEchantillon]    INT             NOT NULL,
    [CleGroupeP]           SMALLINT        NULL,
    [CleDosParametre]      INT             IDENTITY (1, 1) NOT NULL,
    [CleParametre]         INT             NULL,
    [CleMatrice]           SMALLINT        NULL,
    [CleLaboratoire]       INT             NULL,
    [CleSpecification]     INT             NULL,
    [CleSpcParametre]      INT             NULL,
    [DatDebutAnalyse]      SMALLDATETIME   NULL,
    [DatFinAnalyse]        SMALLDATETIME   NULL,
    [OpeResultat]          VARCHAR (10)    NULL,
    [ValResultat_N]        REAL            NULL,
    [NbrDecimale]          TINYINT         NULL,
    [ValResultat_A]        VARCHAR (255)   NULL,
    [ValResultat_D]        SMALLDATETIME   NULL,
    [ValResultat_L]        INT             NULL,
    [CleInterpretation]    SMALLINT        NULL,
    [ValLimInferieure]     REAL            NULL,
    [ValLimSuperieure]     REAL            NULL,
    [ValLimDetection]      DECIMAL (15, 4) NULL,
    [ValLimQuantification] DECIMAL (15, 4) NULL,
    [ValLimSaturation]     DECIMAL (15, 4) NULL,
    [ValIncertitude]       DECIMAL (15, 4) NULL,
    [TxtMetBorne]          VARCHAR (100)   NULL,
    [TxtSpcBorne]          VARCHAR (100)   NULL,
    [CleFeuille]           INT             NULL,
    [EstAccredite]         BIT             CONSTRAINT [DF_Lms0_DosParametre_EstAccredite] DEFAULT ((0)) NOT NULL,
    [EstObligatoire]       BIT             CONSTRAINT [DF_Lms0_DosParametre_EstObligatoire] DEFAULT ((0)) NULL,
    [NumOrdre]             SMALLINT        NULL,
    [EstImprimable]        BIT             CONSTRAINT [DF_Lms0_DosParametre_EstImprimable] DEFAULT ((1)) NULL,
    [EstExportable]        BIT             CONSTRAINT [DF_Lms0_DosParametre_EstExportable] DEFAULT ((1)) NULL,
    [EstFacturable]        BIT             CONSTRAINT [DF_Lms0_DosParametre_EstFacturable] DEFAULT ((1)) NULL,
    [PrxUnitaire]          DECIMAL (10, 2) NULL,
    [EstSaisi]             BIT             CONSTRAINT [DF_Lms0_DosParametre_EstSaisi] DEFAULT ((0)) NOT NULL,
    [DatSaisie]            SMALLDATETIME   NULL,
    [DatValidation]        SMALLDATETIME   NULL,
    [CleUniteT]            SMALLINT        NULL,
    [ClePrdGroupeP]        INT             NULL,
    [EstHorsForfait]       BIT             CONSTRAINT [DF_Lms0_DosParametre_EstHorsForfait] DEFAULT ((0)) NOT NULL,
    [TypUsage]             VARCHAR (1)     CONSTRAINT [DF_Lms0_DosParametre_TypUsage] DEFAULT ('') NOT NULL,
    [TxtIncertitude]       VARCHAR (100)   NULL,
    [EstHorsFormat]        BIT             NOT NULL,
    [TxtResultat]          VARCHAR (255)   NULL,
    [CleExpUnite]          INT             NULL,
    CONSTRAINT [PK_Lms0_DosParametre] PRIMARY KEY CLUSTERED ([CleDosParametre] ASC),
    CONSTRAINT [FK1_Lms0_DosParametre] FOREIGN KEY ([CleDossier]) REFERENCES [SA_TMPI].[Lms0_DosDossier] ([CleDossier]),
    CONSTRAINT [FK10_Lms0_DosParametre] FOREIGN KEY ([CleGroupeP]) REFERENCES [SA_TMPI].[Lmp_GrpGroupeP] ([CleGroupeP]),
    CONSTRAINT [FK11_Lms0_DosParametre] FOREIGN KEY ([CleParametre]) REFERENCES [SA_TMPI].[Lmp_ParParametre] ([CleParametre]),
    CONSTRAINT [FK12_Lms0_DosParametre] FOREIGN KEY ([CleUniteT]) REFERENCES [SA_TMPI].[Lmp_UniUniteT] ([CleUniteT]),
    CONSTRAINT [FK13_Lms0_DosParametre] FOREIGN KEY ([CleMatrice]) REFERENCES [SA_TMPI].[Lmp_MatMatrice] ([CleMatrice]),
    CONSTRAINT [FK15_Lms0_DosParametre] FOREIGN KEY ([CleInterpretation]) REFERENCES [SA_TMPI].[Lmp_Par_Interp] ([CleInterp]),
    CONSTRAINT [FK2_Lms0_DosParametre] FOREIGN KEY ([CleDosEchantillon]) REFERENCES [SA_TMPI].[Lms0_DosEchantillon] ([CleDosEchantillon]),
    CONSTRAINT [FK5_Lms0_DosParametre] FOREIGN KEY ([CleLaboratoire]) REFERENCES [SA_TMPI].[Gen_TrsTiers] ([CleTiers])
);

