CREATE TABLE [SA_TMPI].[Lms_DemParametre] (
    [CleDemParametre]   INT             IDENTITY (1, 1) NOT NULL,
    [CleDemande]        INT             NOT NULL,
    [CleDemPrelevement] INT             NULL,
    [CleDemEchantillon] INT             NULL,
    [CleGroupeP]        SMALLINT        NULL,
    [CleMatrice]        SMALLINT        NULL,
    [CleAnalyte]        SMALLINT        NULL,
    [CleMethode]        SMALLINT        NULL,
    [CleParametre]      INT             NULL,
    [CleUnite]          SMALLINT        NULL,
    [EstDeTerrain]      BIT             NOT NULL,
    [TypUsage]          VARCHAR (1)     NULL,
    [TxtParametre]      VARCHAR (255)   NULL,
    [ValResultat_N]     DECIMAL (15, 5) NULL,
    [ValResultat_A]     VARCHAR (255)   NULL,
    [ValResultat_L]     SMALLINT        NULL,
    CONSTRAINT [PK_Lms_DemParametre] PRIMARY KEY CLUSTERED ([CleDemParametre] ASC),
    CONSTRAINT [FK1_Lms_DemParametre] FOREIGN KEY ([CleDemande]) REFERENCES [SA_TMPI].[Lms_DemDemande] ([CleDemande]),
    CONSTRAINT [FK10_Lms_DemParametre] FOREIGN KEY ([ValResultat_L]) REFERENCES [SA_TMPI].[Lmp_Par_Valeur] ([CleValeur]),
    CONSTRAINT [FK2_Lms_DemParametre] FOREIGN KEY ([CleDemPrelevement]) REFERENCES [SA_TMPI].[Lms_DemPrelevement] ([CleDemPrelevement]),
    CONSTRAINT [FK3_Lms_DemParametre] FOREIGN KEY ([CleDemEchantillon]) REFERENCES [SA_TMPI].[Lms_DemEchantillon] ([CleDemEchantillon]),
    CONSTRAINT [FK4_Lms_DemParametre] FOREIGN KEY ([CleGroupeP]) REFERENCES [SA_TMPI].[Lmp_GrpGroupeP] ([CleGroupeP]),
    CONSTRAINT [FK5_Lms_DemParametre] FOREIGN KEY ([CleMatrice]) REFERENCES [SA_TMPI].[Lmp_MatMatrice] ([CleMatrice]),
    CONSTRAINT [FK6_Lms_DemParametre] FOREIGN KEY ([CleParametre]) REFERENCES [SA_TMPI].[Lmp_ParParametre] ([CleParametre]),
    CONSTRAINT [FK7_Lms_DemParametre] FOREIGN KEY ([CleAnalyte]) REFERENCES [SA_TMPI].[Lmp_AnlAnalyte] ([CleAnalyte]),
    CONSTRAINT [FK8_Lms_DemParametre] FOREIGN KEY ([CleMethode]) REFERENCES [SA_TMPI].[Lmp_MetMethode] ([CleMethode]),
    CONSTRAINT [FK9_Lms_DemParametre] FOREIGN KEY ([CleUnite]) REFERENCES [SA_TMPI].[Lmp_UniUniteT] ([CleUniteT]),
    CONSTRAINT [UN_Lms_DemParametre] UNIQUE NONCLUSTERED ([CleDemande] ASC, [CleDemPrelevement] ASC, [CleDemEchantillon] ASC, [CleGroupeP] ASC, [CleAnalyte] ASC, [CleMethode] ASC, [CleParametre] ASC)
);

