CREATE TABLE [SA_TMPI].[Sdr9_DemPrelev] (
    [ClePrelev]      INT            NOT NULL,
    [CodPrelev]      VARCHAR (50)   NOT NULL,
    [LibPrelev]      VARCHAR (100)  NULL,
    [TxtPrelev]      VARCHAR (2000) NULL,
    [TxtLocalExacte] VARCHAR (80)   NULL,
    [TxtRisque]      VARCHAR (2000) NULL,
    [NumOrdre]       SMALLINT       NULL,
    [DatPrelev]      SMALLDATETIME  NULL,
    [DelPrelev]      SMALLINT       NULL,
    [HeuPrelev]      SMALLDATETIME  NULL,
    [ValDuree]       VARCHAR (8)    NULL,
    [EstConforme]    BIT            NULL,
    [EstAccredite]   BIT            NULL,
    [EstSsReserve]   BIT            NULL,
    [CleDemande]     INT            NULL,
    [CleStation]     INT            NULL,
    [CleStationT]    INT            NULL,
    [CleLocal]       INT            NULL,
    [CleLocalT]      INT            NULL,
    [CodSupport]     VARCHAR (50)   NULL,
    [CleSupportS]    SMALLINT       NOT NULL,
    [CleSupportT]    SMALLINT       NOT NULL,
    [CodMethode]     VARCHAR (50)   NULL,
    [CleMethodeS]    SMALLINT       NULL,
    [CleMethodeT]    SMALLINT       NULL,
    [ClePayeur]      SMALLINT       NULL,
    [ClePreleveur]   SMALLINT       NULL,
    [ClePreleveurT]  SMALLINT       NULL,
    [CodUsage]       VARCHAR (50)   NULL,
    [CleUsageS]      SMALLINT       NULL,
    [CleUsageT]      SMALLINT       NULL,
    [CodNature]      VARCHAR (50)   NULL,
    [CleNatureS]     SMALLINT       NULL,
    [CleNatureT]     SMALLINT       NULL,
    [CodNorme]       VARCHAR (50)   NULL,
    [CleNormeS]      SMALLINT       NULL,
    [CleNormeT]      SMALLINT       NULL,
    [CodMotif]       VARCHAR (50)   NULL,
    [CleMotifS]      SMALLINT       NOT NULL,
    [CleMotifT]      SMALLINT       NOT NULL,
    CONSTRAINT [PK_Sdr9_DemPrelev] PRIMARY KEY CLUSTERED ([ClePrelev] ASC),
    CONSTRAINT [UN_Sdr9_DemPrelev] UNIQUE NONCLUSTERED ([ClePrelev] ASC, [CodPrelev] ASC)
);

