CREATE TABLE [SA_TMPI].[Sdr9_DemAnalyse] (
    [CleAnalyse]        INT             NOT NULL,
    [CleAnalyseT]       INT             NOT NULL,
    [CleDemAnalyseLims] INT             NULL,
    [CleDemGroupe]      INT             NULL,
    [CleDemande]        INT             NULL,
    [CleGroupeS]        INT             NOT NULL,
    [CleGroupeT]        INT             NOT NULL,
    [TxtAnalyse]        VARCHAR (2000)  NULL,
    [CodUnite]          VARCHAR (50)    NULL,
    [CleUniteS]         SMALLINT        NOT NULL,
    [CleUniteT]         SMALLINT        NOT NULL,
    [CodParametre]      VARCHAR (50)    NULL,
    [CleParametreS]     SMALLINT        NOT NULL,
    [CleParametreT]     SMALLINT        NOT NULL,
    [CodFraction]       VARCHAR (50)    NULL,
    [CleFractionS]      SMALLINT        NOT NULL,
    [CleFractionT]      SMALLINT        NOT NULL,
    [CodMethode]        VARCHAR (50)    NULL,
    [CleMethodeS]       SMALLINT        NOT NULL,
    [CleMethodeT]       SMALLINT        NOT NULL,
    [CleEchant]         INT             NULL,
    [ClePayeur]         SMALLINT        NULL,
    [ValResAna]         DECIMAL (15, 5) NULL,
    [CodRemAna]         VARCHAR (2)     NULL,
    [InsituAna]         VARCHAR (1)     NULL,
    [ValLimDetec]       DECIMAL (15, 5) NULL,
    [ValLimQuant]       DECIMAL (15, 5) NULL,
    [ValLimSatur]       DECIMAL (15, 5) NULL,
    [EstAccreAna]       VARCHAR (1)     NULL,
    [EstConfirm]        VARCHAR (1)     NULL,
    [EstSsReserve]      VARCHAR (1)     NULL,
    [ValIncert]         DECIMAL (15, 5) NULL,
    [TxtRefAna]         VARCHAR (200)   NULL,
    [ValRdtExtract]     REAL            NULL,
    [ValVolFiltre]      REAL            NULL,
    CONSTRAINT [PK_Sdr9_DemAnalyse] PRIMARY KEY CLUSTERED ([CleAnalyse] ASC)
);

