CREATE TABLE [SA_TMPI].[t_EquipMInterv] (
    [CleEquipMInterv] INT             IDENTITY (1, 1) NOT NULL,
    [CleEquip]        INT             NOT NULL,
    [CleFamille]      INT             NOT NULL,
    [LibInterv]       VARCHAR (100)   NOT NULL,
    [DurInterv]       SMALLINT        CONSTRAINT [DF_t_EquipMInterv_DurInterv] DEFAULT ((0)) NOT NULL,
    [MntInterv]       DECIMAL (15, 2) CONSTRAINT [DF_t_EquipMInterv_MntInterv] DEFAULT ((0)) NOT NULL,
    [CleFourn]        SMALLINT        NOT NULL,
    [CleRespon]       SMALLINT        NOT NULL,
    [CleDocument1]    INT             NULL,
    [CleDocument2]    INT             NULL,
    [CleContrat]      INT             NULL,
    [DatInterv_V]     DATETIME        NULL,
    [DatInterv_Q]     INT             CONSTRAINT [DF_t_EquipMInterv_DatInterv_Q] DEFAULT ((0)) NULL,
    [DatInterv_U]     TINYINT         CONSTRAINT [DF_t_EquipMInterv_DatInterv_U] DEFAULT ((0)) NULL,
    [CptInterv_V]     INT             CONSTRAINT [DF_t_EquipMInterv_CptInterv_V] DEFAULT ((0)) NULL,
    [CptInterv_Q]     INT             CONSTRAINT [DF_t_EquipMInterv_CptInterv_Q] DEFAULT ((0)) NULL,
    [TxtConsigne]     VARCHAR (255)   NULL,
    [IndPlanifie]     BIT             CONSTRAINT [DF_t_EquipMInterv_IndPlanifie] DEFAULT ((0)) NOT NULL,
    [NbrInterv1]      INT             CONSTRAINT [DF_t_EquipMInterv_NbrInterv1] DEFAULT ((0)) NOT NULL,
    [NbrInterv2]      INT             CONSTRAINT [DF_t_EquipMInterv_NbrInterv2] DEFAULT ((0)) NOT NULL,
    [DatSaisie]       DATETIME        NOT NULL,
    [CleOperateur]    SMALLINT        NOT NULL,
    [NumVersion]      TINYINT         NULL,
    [NbrModif]        TINYINT         NULL,
    [DatValidation]   DATETIME        NULL,
    [CleValideur]     SMALLINT        NULL,
    CONSTRAINT [FK1_t_EquipMInterv] FOREIGN KEY ([CleEquip]) REFERENCES [SA_TMPI].[t_Equip] ([CleEquip]),
    CONSTRAINT [FK2_t_EquipMInterv] FOREIGN KEY ([CleFourn]) REFERENCES [SA_TMPI].[t_Fourn] ([CleFourn])
);

