CREATE TABLE [SA_TMPI].[Edi_ResDossier] (
    [CleDossier]                  INT           NOT NULL,
    [CleSI]                       TINYINT       NOT NULL,
    [TypReferentiel]              TINYINT       NOT NULL,
    [NumDossier]                  VARCHAR (100) NOT NULL,
    [NumDemande]                  VARCHAR (100) NULL,
    [DatDemande]                  SMALLDATETIME NULL,
    [DatDemDebut]                 SMALLDATETIME NULL,
    [DatDemFin]                   SMALLDATETIME NULL,
    [DatIntervention]             SMALLDATETIME NOT NULL,
    [DatReception]                SMALLDATETIME NULL,
    [DatValidation]               SMALLDATETIME NULL,
    [TxtDossier]                  VARCHAR (255) NULL,
    [CleMotif]                    INT           NULL,
    [CleMotif_Ref]                INT           NULL,
    [CleEmetteur]                 INT           NOT NULL,
    [CleTypIdentEmetteur]         INT           NULL,
    [CleTypIdentEmetteur_Ref]     INT           NULL,
    [CleDestinataire]             INT           NOT NULL,
    [CleTypIdentDestinataire]     INT           NULL,
    [CleTypIdentDestinataire_Ref] INT           NULL,
    [CleClient]                   INT           NULL,
    [CleTypIdentClient]           INT           NULL,
    [CleTypIdentClient_Ref]       INT           NULL,
    [CleOrgPreleveur]             INT           NULL,
    [CleTypIdentOrgPreleveur]     INT           NULL,
    [CleTypIdentOrgPreleveur_Ref] INT           NULL,
    [CleAtelier]                  INT           NULL,
    [CleTypIdentAtelier]          INT           NULL,
    [CleTypIdentAtelier_Ref]      INT           NULL,
    [ClePayeur]                   INT           NULL,
    [CleTypIdentPayeur]           INT           NULL,
    [CleTypIdentPayeur_Ref]       INT           NULL,
    [ClePrescripteur]             INT           NULL,
    [CleTypIdentPrescripteur]     INT           NULL,
    [CleTypIdentPrescripteur_Ref] INT           NULL,
    [NivPrelevement]              CHAR (1)      NOT NULL,
    [EstComplet]                  BIT           NOT NULL,
    CONSTRAINT [PK_Edi_ResDossier] PRIMARY KEY CLUSTERED ([CleDossier] ASC)
);

