CREATE TABLE [SA_TMPI].[Gen_Cpt_MNumero] (
    [CleMNumero]      SMALLINT      IDENTITY (1, 1) NOT NULL,
    [CleMNumero_C]    SMALLINT      NULL,
    [CleMNumero_H]    SMALLINT      NOT NULL,
    [CodMNumero]      VARCHAR (50)  NOT NULL,
    [LibMNumero]      VARCHAR (100) NOT NULL,
    [TxtMNumero]      VARCHAR (255) NULL,
    [TypCompteur]     SMALLINT      NOT NULL,
    [CleCompteur]     SMALLINT      NOT NULL,
    [ValPrefixe1]     VARCHAR (50)  NULL,
    [ValDate1]        VARCHAR (50)  NULL,
    [ValPrefixe2]     VARCHAR (50)  NULL,
    [NbrCaractere]    TINYINT       CONSTRAINT [DF_Gen_Cpt_MNumero_NbrCaractere] DEFAULT ((5)) NOT NULL,
    [ValSuffixe1]     VARCHAR (50)  NULL,
    [ValDate2]        VARCHAR (50)  NULL,
    [ValSuffixe2]     VARCHAR (50)  NULL,
    [TxtSubstitution] VARCHAR (50)  NULL,
    [EstActif]        BIT           CONSTRAINT [DF_Gen_Cpt_MNumero_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]     SMALLDATETIME CONSTRAINT [DF_Gen_Cpt_MNumero_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]     SMALLINT      CONSTRAINT [DF_Gen_Cpt_MNumero_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]        SMALLDATETIME NULL,
    [CleOperateur]    SMALLINT      NULL,
    [DatValidation]   SMALLDATETIME NULL,
    [CleValideur]     SMALLINT      NULL,
    [CleExterne]      INT           NULL,
    [CleOrigine]      TINYINT       NULL,
    [CleSecteur]      SMALLINT      NULL,
    [CleService]      SMALLINT      NULL,
    CONSTRAINT [PK_Gen_Cpt_MNumero] PRIMARY KEY CLUSTERED ([CleMNumero] ASC),
    CONSTRAINT [FK1_Gen_Cpt_MNumero] FOREIGN KEY ([CleCompteur]) REFERENCES [SA_TMPI].[Gen_CptCompteur] ([CleCompteur]),
    CONSTRAINT [FK2_Gen_Cpt_MNumero] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK3_Gen_Cpt_MNumero] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN1_Gen_Cpt_MNumero] UNIQUE NONCLUSTERED ([CodMNumero] ASC, [CleMNumero_H] ASC)
);

