CREATE TABLE [SA_TMPI].[Lmp_ParParametre] (
    [CleSecteur]          SMALLINT       NULL,
    [CleService]          SMALLINT       NULL,
    [CleAnalyte]          SMALLINT       NULL,
    [CleMethode]          SMALLINT       NULL,
    [CleFamille]          SMALLINT       NULL,
    [CleParametre]        INT            IDENTITY (1, 1) NOT NULL,
    [CleParametre_C]      INT            NULL,
    [CleParametre_H]      INT            NOT NULL,
    [CodParametre]        VARCHAR (50)   NOT NULL,
    [AbvParametre]        NVARCHAR (25)  NULL,
    [LibParametre]        VARCHAR (100)  NOT NULL,
    [LibParametre_I]      NVARCHAR (100) NULL,
    [TxtParametre]        NVARCHAR (255) NULL,
    [NumOrdre]            SMALLINT       CONSTRAINT [DF_Lmp_ParParametre_NumOrdre] DEFAULT ((999)) NOT NULL,
    [CleUniteT]           SMALLINT       NULL,
    [TypDonnee]           TINYINT        CONSTRAINT [DF_Lmp_ParParametre_TypDonnee] DEFAULT ((1)) NOT NULL,
    [TypSaisie]           TINYINT        CONSTRAINT [DF_Lmp_ParParametre_TypSaisie] DEFAULT ((0)) NOT NULL,
    [CodTableExterne]     VARCHAR (50)   NULL,
    [NbrCaractere]        TINYINT        NULL,
    [NbrDecimale]         TINYINT        NULL,
    [NbrSignificatif]     TINYINT        NULL,
    [FrmPresentation]     VARCHAR (50)   NULL,
    [CleFormule]          SMALLINT       NULL,
    [NivCalcul]           TINYINT        CONSTRAINT [DF_Lmp_ParParametre_NivCalcul] DEFAULT ((0)) NOT NULL,
    [EstDeTerrain]        BIT            CONSTRAINT [DF_Lmp_ParParametre_EstDeTerrain] DEFAULT ((0)) NOT NULL,
    [EstObligatoire]      BIT            CONSTRAINT [DF_Lmp_ParParametre_EstObligatoire] DEFAULT ((0)) NOT NULL,
    [EstVariableDeCalcul] BIT            CONSTRAINT [DF_Lmp_ParParametre_EstVariableDeCalcul] DEFAULT ((0)) NULL,
    [EstAccredite]        BIT            CONSTRAINT [DF_Lmp_ParParametre_EstAccredite] DEFAULT ((0)) NULL,
    [EstImprimable]       BIT            CONSTRAINT [DF_Lmp_ParParametre_EstImprimable] DEFAULT ((1)) NOT NULL,
    [EstExportable]       BIT            CONSTRAINT [DF_Lmp_ParParametre_EstExportable] DEFAULT ((1)) NOT NULL,
    [EstFacturable]       BIT            CONSTRAINT [DF_Lmp_ParParametre_EstFacturable] DEFAULT ((1)) NOT NULL,
    [CodAlias_I]          NVARCHAR (50)  NULL,
    [CleLaboratoire]      INT            NULL,
    [EstActif]            BIT            CONSTRAINT [DF_Lmp_ParParametre_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]         SMALLDATETIME  CONSTRAINT [DF_Lmp_ParParametre_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]         SMALLINT       CONSTRAINT [DF_Lmp_ParParametre_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]            SMALLDATETIME  NULL,
    [CleOperateur]        SMALLINT       NULL,
    [DatValidation]       SMALLDATETIME  NULL,
    [CleValideur]         SMALLINT       NULL,
    [CleExterne]          INT            NULL,
    [CleOrigine]          INT            NULL,
    [CleFormat]           TINYINT        NULL,
    [PosRecherche]        TINYINT        NULL,
    [TypValorisation]     TINYINT        CONSTRAINT [DF_Lmp_ParParametre_TypValorisation] DEFAULT ((1)) NOT NULL,
    [CodEtiquette]        VARCHAR (50)   NULL,
    [EstUnComposant]      BIT            CONSTRAINT [DF_Lmp_ParParametre_EstUnComposant] DEFAULT ((0)) NOT NULL,
    [EstQteFacturee]      BIT            CONSTRAINT [DF_Lmp_ParParametre_EstQteFacturee] DEFAULT ((0)) NOT NULL,
    [EstPrxFacture]       BIT            CONSTRAINT [DF_Lmp_ParParametre_EstPrxFacture] DEFAULT ((0)) NOT NULL,
    [DurPrelevement_P]    SMALLINT       NULL,
    [CleParametre_S]      INT            NULL,
    [CleEtape]            TINYINT        NULL,
    CONSTRAINT [PK_Lmp_ParParametre] PRIMARY KEY CLUSTERED ([CleParametre] ASC),
    CONSTRAINT [FK1_Lmp_ParParametre] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK10_Lmp_ParParametre] FOREIGN KEY ([CleAnalyte]) REFERENCES [SA_TMPI].[Lmp_AnlAnalyte] ([CleAnalyte]),
    CONSTRAINT [FK11_Lmp_ParParametre] FOREIGN KEY ([CleMethode]) REFERENCES [SA_TMPI].[Lmp_MetMethode] ([CleMethode]),
    CONSTRAINT [FK12_Lmp_ParParametre] FOREIGN KEY ([CleUniteT]) REFERENCES [SA_TMPI].[Lmp_UniUniteT] ([CleUniteT]),
    CONSTRAINT [FK13_Lmp_ParParametre] FOREIGN KEY ([CleFormule]) REFERENCES [SA_TMPI].[LmsP_Par_Formule] ([CleFormule]),
    CONSTRAINT [FK2_Lmp_ParParametre] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN_Lmp_ParParametre] UNIQUE NONCLUSTERED ([CodParametre] ASC)
);

