CREATE TABLE [SA_TMPI].[Lmp_GrpGroupeP] (
    [CleSecteur]        SMALLINT        NULL,
    [CleService]        SMALLINT        NULL,
    [CleGroupeP]        SMALLINT        IDENTITY (1, 1) NOT NULL,
    [CleGroupeP_C]      SMALLINT        NULL,
    [CleGroupeP_H]      SMALLINT        NOT NULL,
    [TypGroupeP]        TINYINT         CONSTRAINT [DF_Lmp_GrpGroupeP_TypGroupeP] DEFAULT ((2)) NOT NULL,
    [CodGroupeP]        VARCHAR (50)    NOT NULL,
    [AbvGroupeP]        VARCHAR (25)    NULL,
    [LibGroupeP]        VARCHAR (200)   NOT NULL,
    [NivGroupeP]        TINYINT         CONSTRAINT [DF_Lmp_GrpGroupeP_NivGroupeP] DEFAULT ((1)) NOT NULL,
    [TxtGroupeP]        VARCHAR (255)   NULL,
    [EstPlanAnalyse]    BIT             CONSTRAINT [DF_Lmp_GrpGroupeP_EstPlanAnalyse] DEFAULT ((1)) NOT NULL,
    [CleSpecification]  SMALLINT        NULL,
    [TypInterpretation] TINYINT         CONSTRAINT [DF_Lmp_GrpGroupeP_TypInterpretation] DEFAULT ((0)) NOT NULL,
    [EstFacturable]     BIT             CONSTRAINT [DF_Lmp_GrpGroupeP_EstFacturable] DEFAULT ((1)) NULL,
    [EstForfaitaire]    BIT             CONSTRAINT [DF_Lmp_GrpGroupeP_EstForfaitaire] DEFAULT ((1)) NOT NULL,
    [CleTarif]          SMALLINT        CONSTRAINT [DF_Lmp_GrpGroupeP_CleTarif] DEFAULT ((0)) NULL,
    [EstActif]          BIT             CONSTRAINT [DF_Lmp_GrpGroupeP_EstActif] DEFAULT ((1)) NOT NULL,
    [DatCreation]       SMALLDATETIME   CONSTRAINT [DF_Lmp_GrpGroupeP_DatCreation] DEFAULT (getdate()) NOT NULL,
    [CleCreateur]       SMALLINT        CONSTRAINT [DF_Lmp_GrpGroupeP_CleCreateur] DEFAULT ((0)) NOT NULL,
    [DatModif]          SMALLDATETIME   NULL,
    [CleOperateur]      SMALLINT        NULL,
    [DatValidation]     SMALLDATETIME   NULL,
    [CleValideur]       SMALLINT        NULL,
    [CleExterne]        INT             NULL,
    [CleOrigine]        SMALLINT        NULL,
    [LibGroupeP_I]      VARCHAR (500)   NOT NULL,
    [EstOptionnel]      BIT             CONSTRAINT [DF_Lmp_GrpGroupeP_EstOptionnel] DEFAULT ((0)) NOT NULL,
    [CleCompetence_V]   SMALLINT        NULL,
    [DurPrelevement_G]  SMALLINT        NULL,
    [NumOrdre]          INT             CONSTRAINT [DF_Lmp_GrpGroupeP_NumOrdre] DEFAULT ((999)) NOT NULL,
    [CleEtape]          TINYINT         NULL,
    [TypFacturation]    TINYINT         CONSTRAINT [DF_Lmp_GrpGroupeP_TypFacturation] DEFAULT ((0)) NOT NULL,
    [MntForfait]        DECIMAL (10, 2) NULL,
    [CleTVA]            SMALLINT        NULL,
    CONSTRAINT [PK_Lmp_GrpGroupeP] PRIMARY KEY CLUSTERED ([CleGroupeP] ASC),
    CONSTRAINT [FK1_Lmp_GrpGroupeP] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Gen_SocSecteur] ([CleSecteur]),
    CONSTRAINT [FK2_Lmp_GrpGroupeP] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [FK3_Lmp_GrpGroupeP] FOREIGN KEY ([CleSpecification]) REFERENCES [SA_TMPI].[Lmp_SpcSpecification] ([CleSpecification]),
    CONSTRAINT [UN_Lmp_GrpGroupeP] UNIQUE NONCLUSTERED ([CodGroupeP] ASC)
);

