CREATE TABLE [SA_TMPI].[t_Article] (
    [CleFamille]           SMALLINT        NULL,
    [CleSFamille]          SMALLINT        NULL,
    [CleArticle]           INT             IDENTITY (1, 1) NOT NULL,
    [CodArticle]           VARCHAR (60)    NOT NULL,
    [LibArticle]           VARCHAR (2000)  NOT NULL,
    [TxtArticle]           VARCHAR (255)   NULL,
    [LibTArticle]          VARCHAR (2000)  NULL,
    [RefDocum]             VARCHAR (255)   NULL,
    [RefSecur]             VARCHAR (255)   NULL,
    [RefUtil]              VARCHAR (255)   NULL,
    [CleUniteB]            SMALLINT        NOT NULL,
    [NbrDecimal]           TINYINT         CONSTRAINT [DF_t_Article_NbrDecimal] DEFAULT ((2)) NOT NULL,
    [CleEtiquette]         TINYINT         NULL,
    [CleImput]             SMALLINT        NULL,
    [CleTVA]               TINYINT         NOT NULL,
    [PrxUnitaire]          DECIMAL (15, 4) CONSTRAINT [DF_t_Article_PrxUnitaire] DEFAULT ((0)) NOT NULL,
    [CleDevise]            TINYINT         NULL,
    [DelLivraison]         TINYINT         NULL,
    [IndCommun]            BIT             CONSTRAINT [DF_t_Article_IndCommun] DEFAULT ((0)) NOT NULL,
    [IndLot]               BIT             CONSTRAINT [DF_t_Article_IndLot] DEFAULT ((1)) NOT NULL,
    [IndAppro]             BIT             CONSTRAINT [DF_t_Article_IndAppro] DEFAULT ((0)) NOT NULL,
    [IndValidLot]          BIT             CONSTRAINT [DF_t_Article_IndValidLot] DEFAULT ((0)) NOT NULL,
    [IndActif]             BIT             CONSTRAINT [DF_t_Article_IndActif] DEFAULT ((1)) NOT NULL,
    [IndFabri]             BIT             CONSTRAINT [DF_t_Article_IndFabri] DEFAULT ((0)) NOT NULL,
    [IndCatal]             BIT             CONSTRAINT [DF_t_Article_IndCatal] DEFAULT ((0)) NOT NULL,
    [IndTestConf]          BIT             CONSTRAINT [DF_t_Article_IndTestConf] DEFAULT ((0)) NOT NULL,
    [IndNQualif]           BIT             CONSTRAINT [DF_t_Article_IndNQualif] DEFAULT ((0)) NOT NULL,
    [IndSuiviInd]          BIT             CONSTRAINT [DF_t_Article_IndSuiviInd] DEFAULT ((0)) NOT NULL,
    [CleArticleTarif]      INT             NULL,
    [CleFourn]             SMALLINT        NULL,
    [CleFabricant]         SMALLINT        NULL,
    [CleDomaine]           SMALLINT        NULL,
    [CleStock]             SMALLINT        NULL,
    [CleNomenc]            SMALLINT        NULL,
    [CleAffect]            SMALLINT        NULL,
    [DelAlerte]            SMALLINT        CONSTRAINT [DF_t_Article_DelAlerte] DEFAULT ((7)) NOT NULL,
    [DelPeremption]        SMALLINT        CONSTRAINT [DF_t_Article_DelPeremption] DEFAULT ((0)) NULL,
    [DatSaisie]            DATETIME        CONSTRAINT [DF_t_Article_DatSaisie] DEFAULT (getdate()) NOT NULL,
    [CleOperateur]         SMALLINT        CONSTRAINT [DF_t_Article_CleOperateur] DEFAULT ((0)) NOT NULL,
    [NbrModif]             TINYINT         CONSTRAINT [DF_t_Article_NbrModif] DEFAULT ((0)) NULL,
    [NumVersion]           TINYINT         CONSTRAINT [DF_t_Article_NumVersion] DEFAULT ((0)) NULL,
    [DatValidation]        DATETIME        NULL,
    [CleValideur]          SMALLINT        NULL,
    [DurVieMin]            SMALLINT        CONSTRAINT [DF_t_Article_DurVieMin] DEFAULT ((0)) NULL,
    [DatCommande]          SMALLDATETIME   NULL,
    [TxtRecette]           VARCHAR (4000)  NULL,
    [EstCritique]          BIT             CONSTRAINT [DF_t_Article_EstCritique] DEFAULT ((0)) NOT NULL,
    [TypLotGenere]         TINYINT         CONSTRAINT [DF_t_Article_TypLotGenere] DEFAULT ((0)) NOT NULL,
    [EstCommandable]       BIT             CONSTRAINT [DF_t_Article_EstCommandable] DEFAULT ((0)) NOT NULL,
    [EstComposable]        BIT             CONSTRAINT [DF_t_Article_EstComposable] DEFAULT ((0)) NOT NULL,
    [EstComposantDestocke] BIT             CONSTRAINT [DF_t_Article_EstComposantDestocke] DEFAULT ((0)) NOT NULL,
    [CodAlias]             VARCHAR (50)    NULL,
    [CleProprietaire]      SMALLINT        NULL,
    CONSTRAINT [PK_t_Article] PRIMARY KEY CLUSTERED ([CleArticle] ASC),
    CONSTRAINT [FK1_t_Article] FOREIGN KEY ([CleDomaine]) REFERENCES [SA_TMPI].[t_Domaine] ([CleDomaine]),
    CONSTRAINT [FK2_t_Article] FOREIGN KEY ([CleUniteB]) REFERENCES [SA_TMPI].[t_Unite] ([CleUnite]),
    CONSTRAINT [FK8_t_Article] FOREIGN KEY ([CleImput]) REFERENCES [SA_TMPI].[t_Imput] ([CleImput]),
    CONSTRAINT [UN1_t_Article] UNIQUE NONCLUSTERED ([CodArticle] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ID1_t_Article]
    ON [SA_TMPI].[t_Article]([LibArticle] ASC) WITH (FILLFACTOR = 90);

