CREATE TABLE [SA_TMPI].[t_BudgetALig] (
    [CleBudget]        SMALLINT        NOT NULL,
    [CleBudgetVersion] INT             NOT NULL,
    [CleAffect]        SMALLINT        NOT NULL,
    [MntPrevu]         DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu] DEFAULT ((0)) NOT NULL,
    [MntPrevu_01]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_01] DEFAULT ((0)) NOT NULL,
    [MntPrevu_02]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_02] DEFAULT ((0)) NOT NULL,
    [MntPrevu_03]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_03] DEFAULT ((0)) NOT NULL,
    [MntPrevu_04]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_04] DEFAULT ((0)) NOT NULL,
    [MntPrevu_05]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_05] DEFAULT ((0)) NOT NULL,
    [MntPrevu_06]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_06] DEFAULT ((0)) NOT NULL,
    [MntPrevu_07]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_07] DEFAULT ((0)) NOT NULL,
    [MntPrevu_08]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_08] DEFAULT ((0)) NOT NULL,
    [MntPrevu_09]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_09] DEFAULT ((0)) NOT NULL,
    [MntPrevu_10]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_10] DEFAULT ((0)) NOT NULL,
    [MntPrevu_11]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_11] DEFAULT ((0)) NOT NULL,
    [MntPrevu_12]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntPrevu_12] DEFAULT ((0)) NOT NULL,
    [MntConsomme]      DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme] DEFAULT ((0)) NOT NULL,
    [MntConsomme_01]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_01] DEFAULT ((0)) NOT NULL,
    [MntConsomme_02]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_02] DEFAULT ((0)) NOT NULL,
    [MntConsomme_03]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_03] DEFAULT ((0)) NOT NULL,
    [MntConsomme_04]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_04] DEFAULT ((0)) NOT NULL,
    [MntConsomme_05]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_05] DEFAULT ((0)) NOT NULL,
    [MntConsomme_06]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_06] DEFAULT ((0)) NOT NULL,
    [MntConsomme_07]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_07] DEFAULT ((0)) NOT NULL,
    [MntConsomme_08]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_08] DEFAULT ((0)) NOT NULL,
    [MntConsomme_09]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_09] DEFAULT ((0)) NOT NULL,
    [MntConsomme_10]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_10] DEFAULT ((0)) NOT NULL,
    [MntConsomme_11]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_11] DEFAULT ((0)) NOT NULL,
    [MntConsomme_12]   DECIMAL (15, 2) CONSTRAINT [DF_t_BudgetALig_MntConsomme_12] DEFAULT ((0)) NOT NULL,
    [ValCoef]          SMALLINT        CONSTRAINT [DF_t_BudgetALig_ValCoef] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_t_BudgetALig] PRIMARY KEY CLUSTERED ([CleAffect] ASC, [CleBudgetVersion] ASC),
    CONSTRAINT [FK1_t_BudgetALig] FOREIGN KEY ([CleBudgetVersion]) REFERENCES [SA_TMPI].[t_BudgetVersion] ([CleBudgetVersion]),
    CONSTRAINT [FK2_t_BudgetALig] FOREIGN KEY ([CleAffect]) REFERENCES [SA_TMPI].[t_BudAffect] ([CleAffect])
);

