CREATE TABLE [SA_TMPI].[t_Equip] (
    [CleEquip]      INT             IDENTITY (1, 1) NOT NULL,
    [CodEquip]      VARCHAR (50)    NOT NULL,
    [LibEquip]      VARCHAR (100)   NOT NULL,
    [TxtEquip]      VARCHAR (255)   NULL,
    [NumInventaire] VARCHAR (25)    NULL,
    [NumSerie]      VARCHAR (25)    NULL,
    [LibTEquip]     VARCHAR (255)   NULL,
    [LibMarque]     VARCHAR (255)   NULL,
    [CleFamille]    SMALLINT        NULL,
    [CleSFamille]   SMALLINT        NULL,
    [RefDocum]      VARCHAR (255)   NULL,
    [RefSecur]      VARCHAR (255)   NULL,
    [RefUtil]       VARCHAR (255)   NULL,
    [CleService]    SMALLINT        NOT NULL,
    [CleLocal]      SMALLINT        NULL,
    [CleFabric]     SMALLINT        NULL,
    [CleFourn]      SMALLINT        NULL,
    [CleFournSAV]   SMALLINT        NULL,
    [ValCompteur]   INT             CONSTRAINT [DF_t_Equip_ValCompteur] DEFAULT ((0)) NOT NULL,
    [CleRespon]     SMALLINT        NULL,
    [DatGarantie]   DATETIME        NULL,
    [DurGarantie]   TINYINT         NULL,
    [CleEtatR]      SMALLINT        NULL,
    [IndHSuivi]     BIT             CONSTRAINT [DF_t_Equip_IndHSuivi] DEFAULT ((0)) NOT NULL,
    [IndEnService]  BIT             CONSTRAINT [DF_t_Equip_IndEnService] DEFAULT ((0)) NOT NULL,
    [IndEnReserve]  BIT             CONSTRAINT [DF_t_Equip_IndEnReserve] DEFAULT ((0)) NOT NULL,
    [DatReception]  DATETIME        NULL,
    [DatMService]   DATETIME        NULL,
    [DatDeclass]    DATETIME        NULL,
    [DatReforme]    DATETIME        NULL,
    [CleCommande]   INT             NULL,
    [NumCommande]   VARCHAR (25)    NULL,
    [DatAchat]      DATETIME        NULL,
    [PrxAchat]      DECIMAL (15, 4) CONSTRAINT [DF_t_Equip_PrxAchat] DEFAULT ((0)) NOT NULL,
    [PrxRenouv]     DECIMAL (15, 4) CONSTRAINT [DF_t_Equip_PrxRenouv] DEFAULT ((0)) NOT NULL,
    [DurAmortis]    TINYINT         CONSTRAINT [DF_t_Equip_DurAmortis] DEFAULT ((0)) NOT NULL,
    [DatSaisie]     DATETIME        NULL,
    [CleOperateur]  SMALLINT        NULL,
    [NbrModif]      TINYINT         NULL,
    [NumVersion]    TINYINT         NULL,
    [DatValidation] DATETIME        NULL,
    [CleValideur]   SMALLINT        NULL,
    [CleAffect]     SMALLINT        NULL,
    [TxtAchat]      VARCHAR (255)   NULL,
    [CleAtelier]    SMALLINT        NULL,
    [NumEngage]     VARCHAR (25)    NULL,
    [NumFacture]    VARCHAR (25)    NULL,
    [DatFacture]    DATETIME        NULL,
    [EstCritique]   BIT             CONSTRAINT [DF_t_Equip_EstCritique] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_t_Equip] PRIMARY KEY CLUSTERED ([CleEquip] ASC),
    CONSTRAINT [FK2_t_Equip] FOREIGN KEY ([CleService]) REFERENCES [SA_TMPI].[Gen_SocService] ([CleService]),
    CONSTRAINT [UN_t_Equip] UNIQUE NONCLUSTERED ([CodEquip] ASC)
);

