CREATE TABLE [SA_TMPI].[Trn_TchTache] (
    [CleTache]               INT            NOT NULL,
    [DatDebut]               SMALLDATETIME  NULL,
    [HeuPrevue]              INT            NULL,
    [EstRVOblige]            BIT            CONSTRAINT [DF_Trn_TchTache_EstRVOblige] DEFAULT ((0)) NOT NULL,
    [AdrRue]                 VARCHAR (1000) NULL,
    [AdrVille]               VARCHAR (100)  NULL,
    [AdrCode]                INT            NULL,
    [DurTache]               SMALLINT       NULL,
    [EstPlanificationForcee] BIT            CONSTRAINT [DF_Trn_TchTache_EstPlanificationForcee] DEFAULT ((0)) NOT NULL,
    [CleTacheParent]         INT            NULL,
    [DurTacheParentMin]      INT            NULL,
    [DurTacheParentMax]      INT            NULL,
    [CleIntervenantImpose]   SMALLINT       NULL,
    [HeuOuvertureLundi]      TIME (7)       NULL,
    [HeuFermetureLundi]      TIME (7)       NULL,
    [HeuOuvertureMardi]      TIME (7)       NULL,
    [HeuFermetureMardi]      TIME (7)       NULL,
    [HeuOuvertureMercredi]   TIME (7)       NULL,
    [HeuFermetureMercredi]   TIME (7)       NULL,
    [HeuOuvertureJeudi]      TIME (7)       NULL,
    [HeuFermetureJeudi]      TIME (7)       NULL,
    [HeuOuvertureVendredi]   TIME (7)       NULL,
    [HeuFermetureVendredi]   TIME (7)       NULL,
    [HeuOuvertureSamedi]     TIME (7)       NULL,
    [HeuFermetureSamedi]     TIME (7)       NULL,
    [HeuOuvertureDimanche]   TIME (7)       NULL,
    [HeuFermetureDimanche]   TIME (7)       NULL,
    [EstRVAConfirmer]        BIT            CONSTRAINT [DF_Trn_TchTacheEstRVAConfirmer] DEFAULT ((0)) NOT NULL,
    [TypVerrouillage]        TINYINT        NULL,
    [EstSuspendue]           BIT            CONSTRAINT [DF_Trn_TchTache_EstSuspendue] DEFAULT ((0)) NOT NULL,
    [DatConfirmationRV]      SMALLDATETIME  NULL,
    [CleSerie]               INT            NULL,
    [EstSerialise]           BIT            CONSTRAINT [DF_Trn_TchTache_EstSerialise] DEFAULT ((0)) NOT NULL,
    [EstPasPlanifiable]      BIT            CONSTRAINT [DF_Trn_TchTacheEstPasPlanifiable] DEFAULT ((0)) NOT NULL,
    [TypTacheSpeciale]       TINYINT        NULL,
    [NivCompetence]          TINYINT        NULL,
    CONSTRAINT [PK_Trn_TchTache] PRIMARY KEY CLUSTERED ([CleTache] ASC),
    CONSTRAINT [FK1_Trn_TchTache] FOREIGN KEY ([CleTache]) REFERENCES [SA_TMPI].[Trn_DemTache] ([CleDemTache]),
    CONSTRAINT [FK2_Trn_TchTache] FOREIGN KEY ([CleSerie]) REFERENCES [SA_TMPI].[Trn_Tch_Serie] ([CleSerie])
);

