CREATE TABLE [SA_TMPI].[Trn_DemDemande] (
    [CleOrigine]      SMALLINT      NULL,
    [CleClasse]       SMALLINT      NULL,
    [CleDemande]      INT           IDENTITY (1, 1) NOT NULL,
    [TypDemande]      TINYINT       NULL,
    [NumDemande]      VARCHAR (50)  NULL,
    [DatDemande]      SMALLDATETIME NULL,
    [CleMotif]        SMALLINT      NULL,
    [ClePrescripteur] INT           NULL,
    [CleOrgPreleveur] INT           NULL,
    [CleLaboratoire]  INT           NULL,
    [IndSuspension]   BIT           CONSTRAINT [DF_Trn_DemDemande_IndSuspension] DEFAULT ((0)) NULL,
    [DatGeneration]   SMALLDATETIME NULL,
    [NivSaisie]       TINYINT       CONSTRAINT [DF_Trn_DemDemande_NivSaisie] DEFAULT ((0)) NULL,
    [DatCreation]     SMALLDATETIME NULL,
    [CleCreateur]     SMALLINT      NULL,
    [DatModif]        SMALLDATETIME NULL,
    [CleOperateur]    SMALLINT      NULL,
    [DatValidation]   SMALLDATETIME NULL,
    [CleValideur]     SMALLINT      NULL,
    [ClePoint]        INT           NULL,
    [NbrEchant]       TINYINT       NULL,
    [CleProduit]      INT           NULL,
    [DatPrevue]       SMALLDATETIME NULL,
    [HeuPrevue]       SMALLINT      NULL,
    [DatRealisation]  DATETIME      NULL,
    [CleGestionnaire] INT           NULL,
    [NumDevis]        VARCHAR (25)  NULL,
    [CleMatrice]      SMALLINT      NULL,
    [TxtDemande]      VARCHAR (255) NULL,
    [EstActif]        BIT           NULL,
    [CleExterne]      INT           NULL,
    [CleSecteur]      SMALLINT      NOT NULL,
    [CleFamille]      SMALLINT      NULL,
    [ClePayeur]       INT           NULL,
    [NivTraitement]   TINYINT       NOT NULL,
    [CleClient]       INT           NULL,
    [TypSource]       TINYINT       CONSTRAINT [DF_Trn_DemDemandeTypSource] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Trn_DemDemande] PRIMARY KEY CLUSTERED ([CleDemande] ASC),
    CONSTRAINT [FK1_Trn_DemDemande] FOREIGN KEY ([CleOrigine]) REFERENCES [SA_TMPI].[Trp_Dem_Origine] ([CleOrigine]),
    CONSTRAINT [FK2_Trn_DemDemande] FOREIGN KEY ([CleFamille]) REFERENCES [SA_TMPI].[Trp_Dem_Famille] ([CleFamille]),
    CONSTRAINT [FK9_Trn_DemDemande] FOREIGN KEY ([CleSecteur]) REFERENCES [SA_TMPI].[Trp_SecSecteur] ([CleSecteur])
);

