// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // Exercice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Bud_Exercice
    {
        public int CleExercice { get; set; } // CleExercice (Primary key)
        public string CodExercice { get; set; } // CodExercice (length: 100)
        public string LibExercice { get; set; } // LibExercice (length: 200)
        public string TxtExercice { get; set; } // TxtExercice (length: 500)
        public bool EstActif { get; set; } // EstActif
        public System.DateTime DatCreation { get; set; } // DatCreation
        public System.DateTime DatModif { get; set; } // DatModif
        public string CodExterne { get; set; } // CodExterne (length: 100)
        public System.DateTime DatDebut { get; set; } // DatDebut
        public System.DateTime DatFin { get; set; } // DatFin
    }

}
// </auto-generated>
