// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // Compteur
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_Compteur
    {
        public int CleCompteur { get; set; } // CleCompteur (Primary key)
        public string CodCompteur { get; set; } // CodCompteur (length: 100)
        public string LibCompteur { get; set; } // LibCompteur (length: 200)
        public string TxtCompteur { get; set; } // TxtCompteur (length: 500)
        public bool EstActif { get; set; } // EstActif
        public System.DateTime DatCreation { get; set; } // DatCreation
        public System.DateTime DatModif { get; set; } // DatModif
        public string CodExterne { get; set; } // CodExterne (length: 100)
        public short TypCompteur { get; set; } // TypCompteur
        public int? CleSociete { get; set; } // CleSociete
        public int? CleSecteur { get; set; } // CleSecteur
        public int? CleService { get; set; } // CleService
        public byte TypPeriodicite { get; set; } // TypPeriodicite
        public string ValPrefixe1 { get; set; } // ValPrefixe1 (length: 25)
        public string ValFormatDate1 { get; set; } // ValFormatDate1 (length: 25)
        public string ValPrefixe2 { get; set; } // ValPrefixe2 (length: 25)
        public byte NbrDigit { get; set; } // NbrDigit
        public string ValSuffixe1 { get; set; } // ValSuffixe1 (length: 25)
        public string ValFormatDate2 { get; set; } // ValFormatDate2 (length: 25)
        public string ValSuffixe2 { get; set; } // ValSuffixe2 (length: 25)
        public string LstFormatMois { get; set; } // LstFormatMois (length: 500)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Gen_CompteurValeur> Gen_CompteurValeur { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Gen_Societe Gen_Societe { get; set; } // FK_Compteur_CleSociete
        public virtual Gen_SocieteSecteur Gen_SocieteSecteur { get; set; } // FK_Compteur_CleSecteur
        public virtual Gen_SocieteService Gen_SocieteService { get; set; } // FK_Compteur_CleService

        public Gen_Compteur()
        {
            Gen_CompteurValeur = new System.Collections.Generic.List<Gen_CompteurValeur>();
        }
    }

}
// </auto-generated>
