// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // MandatMandataire
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_MandatMandataire
    {
        public int CleMandataire { get; set; } // CleMandataire (Primary key)
        public int CleMandat { get; set; } // CleMandat
        public int ClePersonne { get; set; } // ClePersonne
        public int? CleSociete { get; set; } // CleSociete
        public int? CleSecteur { get; set; } // CleSecteur
        public int? CleService { get; set; } // CleService
        public bool EstSuspendu { get; set; } // EstSuspendu

        // Foreign keys
        public virtual Gen_Mandat Gen_Mandat { get; set; } // FK_MandatMandataire_CleMandat
        public virtual Gen_Personne Gen_Personne { get; set; } // FK_MandatMandataire_ClePersonne
        public virtual Gen_Societe Gen_Societe { get; set; } // FK_MandatMandataire_CleSociete
        public virtual Gen_SocieteSecteur Gen_SocieteSecteur { get; set; } // FK_MandatMandataire_CleSecteur
        public virtual Gen_SocieteService Gen_SocieteService { get; set; } // FK_MandatMandataire_CleService
    }

}
// </auto-generated>
