// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // SocieteSecteur
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_SocieteSecteur
    {
        public int CleSecteur { get; set; } // CleSecteur (Primary key)
        public string CodSecteur { get; set; } // CodSecteur (length: 100)
        public string LibSecteur { get; set; } // LibSecteur (length: 200)
        public string TxtSecteur { get; set; } // TxtSecteur (length: 500)
        public bool EstActif { get; set; } // EstActif
        public System.DateTime DatCreation { get; set; } // DatCreation
        public System.DateTime DatModif { get; set; } // DatModif
        public string CodExterne { get; set; } // CodExterne (length: 100)
        public int CleSociete { get; set; } // CleSociete
        public string AdrRue { get; set; } // AdrRue (length: 200)
        public string AdrCode { get; set; } // AdrCode (length: 10)
        public string AdrVille { get; set; } // AdrVille (length: 100)
        public string AdrPays { get; set; } // AdrPays (length: 100)
        public string NumTelep { get; set; } // NumTelep (length: 25)
        public string NumFax { get; set; } // NumFax (length: 25)
        public string NumEmail { get; set; } // NumEmail (length: 100)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Gen_Compteur> Gen_Compteur { get; set; } // Compteur.FK_Compteur_CleSecteur
        public virtual System.Collections.Generic.ICollection<Gen_MandatMandataire> Gen_MandatMandataire { get; set; } // MandatMandataire.FK_MandatMandataire_CleSecteur
        public virtual System.Collections.Generic.ICollection<Gen_PersonneProfil> Gen_PersonneProfil { get; set; } // PersonneProfil.FK_PersonneProfil_CleSecteur
        public virtual System.Collections.Generic.ICollection<Gen_SocieteService> Gen_SocieteService { get; set; } // SocieteService.FK_SocieteService_CleSecteur

        // Foreign keys
        public virtual Gen_Societe Gen_Societe { get; set; } // FK_SocieteSecteur_CleSociete

        public Gen_SocieteSecteur()
        {
            Gen_Compteur = new System.Collections.Generic.List<Gen_Compteur>();
            Gen_MandatMandataire = new System.Collections.Generic.List<Gen_MandatMandataire>();
            Gen_PersonneProfil = new System.Collections.Generic.List<Gen_PersonneProfil>();
            Gen_SocieteService = new System.Collections.Generic.List<Gen_SocieteService>();
        }
    }

}
// </auto-generated>
