// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // PersonneProfil
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_PersonneProfil
    {
        public int CleProfil { get; set; } // CleProfil (Primary key)
        public int ClePersonne { get; set; } // ClePersonne
        public string CodProfil { get; set; } // CodProfil (length: 100)
        public int? CleSociete { get; set; } // CleSociete
        public int? CleSecteur { get; set; } // CleSecteur
        public int? CleService { get; set; } // CleService

        // Foreign keys
        public virtual Gen_Personne Gen_Personne { get; set; } // FK_PersonneProfil_ClePersonne
        public virtual Gen_Societe Gen_Societe { get; set; } // FK_PersonneProfil_CleSociete
        public virtual Gen_SocieteSecteur Gen_SocieteSecteur { get; set; } // FK_PersonneProfil_CleSecteur
        public virtual Gen_SocieteService Gen_SocieteService { get; set; } // FK_PersonneProfil_CleService
    }

}
// </auto-generated>
