// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // Fourn
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Sto_Fourn
    {
        public int CleFourn { get; set; } // CleFourn (Primary key)
        public string CodFourn { get; set; } // CodFourn (length: 100)
        public string LibFourn { get; set; } // LibFourn (length: 200)
        public string TxtFourn { get; set; } // TxtFourn (length: 500)
        public bool EstActif { get; set; } // EstActif
        public System.DateTime DatCreation { get; set; } // DatCreation
        public System.DateTime DatModif { get; set; } // DatModif
        public string CodExterne { get; set; } // CodExterne (length: 100)
        public string AdrRue { get; set; } // AdrRue (length: 200)
        public string AdrCode { get; set; } // AdrCode (length: 10)
        public string AdrVille { get; set; } // AdrVille (length: 100)
        public string NumTelep { get; set; } // NumTelep (length: 25)
        public string NumTelec { get; set; } // NumTelec (length: 25)
        public string NumEmail { get; set; } // NumEmail (length: 100)
        public string CodCompta { get; set; } // CodCompta (length: 100)
        public string NumClient { get; set; } // NumClient (length: 100)
        public string NumTvaIntra { get; set; } // NumTVAIntra (length: 25)
        public decimal? MntFPort { get; set; } // MntFPort
        public decimal? MntFPortGratuit { get; set; } // MntFPortGratuit
        public decimal? MntCommandeMin { get; set; } // MntCommandeMin
        public byte? DelLivraison { get; set; } // DelLivraison
        public byte? DelPaiement { get; set; } // DelPaiement
        public decimal? ValNote { get; set; } // ValNote
        public byte? TypModeReglement { get; set; } // TypModeReglement
        public bool EstEnvoiMailBonCde { get; set; } // EstEnvoiMailBonCde
        public int? CleProprietaire { get; set; } // CleProprietaire

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Sto_FournBanque> Sto_FournBanque { get; set; } // FournBanque.FK_FournBanque_CleFourn

        // Foreign keys
        public virtual Gen_Personne Gen_Personne { get; set; } // FK_Fourn_CleProprietaire

        public Sto_Fourn()
        {
            Sto_FournBanque = new System.Collections.Generic.List<Sto_FournBanque>();
        }
    }

}
// </auto-generated>
