// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Models.Entities
{

    // FournBanque
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Sto_FournBanque
    {
        public int CleBanque { get; set; } // CleBanque (Primary key)
        public int CleFourn { get; set; } // CleFourn
        public string LibBanque { get; set; } // LibBanque (length: 200)
        public string RibBanque { get; set; } // RibBanque (length: 5)
        public string RibGuichet { get; set; } // RibGuichet (length: 5)
        public string RibCompte { get; set; } // RibCompte (length: 11)
        public string RibCle { get; set; } // RibCle (length: 2)
        public bool EstDefaut { get; set; } // EstDefaut

        // Foreign keys
        public virtual Sto_Fourn Sto_Fourn { get; set; } // FK_FournBanque_CleFourn
    }

}
// </auto-generated>
