//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using ServiceStack;
using ServiceStack.OrmLite;
using Tmpi.Pyrene.Services.ServiceModel;
using Tmpi.Pyrene.Services.ServiceModel.Types;
using Tmpi.Pyrene.Infrastructure;

namespace Tmpi.Pyrene.Services.ServiceInterface
{
	/// <summary>
	/// Service qui traite les requêtes sur les ressources <see cref="GenExercice"/>.
	/// </summary>
	public partial class GenExerciceService : Service
	{
		/// <summary>
		/// 
		/// </summary>
		protected bool GenExerciceCodExerciceEstUnique(GenExercice model)
		{
            var q = Db.From<GenExercice>().Where(x => x.CodExercice == model.CodExercice);
			if (model.CleExercice != 0)
			{
				q.Where(x => x.CleExercice != model.CleExercice);
			}

			return Db.Exists(q);
		}

		/// <summary>
		/// Ajoute la ressource <see cref="GenExercice"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns>Ressource <see cref="GenExercice"/> ajoutée.</returns>
		public GenExercice Post(GenExercice request)
		{
			var id = Db.Insert(request, selectIdentity: true);
			request.CleExercice = (int)id;

			return request;
		}

		/// <summary>
		/// Remplace la ressource <see cref="GenExercice"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public void Put(GenExercice request)
		{
			int count = Db.Update(request);
			if (count == 0)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenExercice), request.CleExercice));
			}
		}

	}
}
