//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using ServiceStack;
using ServiceStack.OrmLite;
using Tmpi.Pyrene.Services.ServiceModel;
using Tmpi.Pyrene.Services.ServiceModel.Types;
using Tmpi.Pyrene.Infrastructure;

namespace Tmpi.Pyrene.Services.ServiceInterface
{
	/// <summary>
	/// Service qui traite les requêtes sur les ressources <see cref="GenMandat" />.
	/// </summary>
	public partial class GenMandatService : Service
	{
		/// <summary>
		/// Retourne la ressource <see cref="GenMandat" /> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns>Ressource <see cref="GenMandat" /> trouvée.</returns>
		/// <exception cref="ArgumentException">La ressource ne contient pas tous les champs spécifiés.</exception>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public GenMandat Get(GetGenMandat request)
		{
            if (!request.Fields.IsNullOrEmpty())
            {
                var errFields = ModelDefinitionHelper.GetUndefinedFields<GenMandat>(request.Fields);
                if (errFields.Any())
                {
                    string str = string.Join(", ", errFields.Select(f => "'" + f + "'"));
                    throw new ArgumentException(
                        string.Format(ServicesErrorMessages.ResourceFieldsNotFound, nameof(GenMandat), str));
                }
            }

            var q = Db.From<GenMandat>().Where<GenMandat>(x => x.CodMandat == request.CodMandat).Select(request.Fields);

			var entity = Db.Single(q);
			if (entity == null)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenMandat), request.Id));
			}

			return entity;
		}

		/// <summary>
		/// Retourne la ressource <see cref="GenMandatMandataire" /> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns>Ressource <see cref="GenMandatMandataire" /> trouvée.</returns>
		/// <exception cref="ArgumentException">La ressource ne contient pas tous les champs spécifiés.</exception>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public GenMandatMandataire Get(GetGenMandatMandataire request)
		{
            if (!request.Fields.IsNullOrEmpty())
            {
                var errFields = ModelDefinitionHelper.GetUndefinedFields<GenMandatMandataire>(request.Fields);
                if (errFields.Any())
                {
                    string str = string.Join(", ", errFields.Select(f => "'" + f + "'"));
                    throw new ArgumentException(
                        string.Format(ServicesErrorMessages.ResourceFieldsNotFound, nameof(GenMandatMandataire), str));
                }
            }

            var q = Db.From<GenMandatMandataire>().Join<GenMandat>().Where<GenMandat>(x => x.CodMandat == request.CodMandat).Join<GenMandatGenMandatMandataire>().Where<GenMandatGenMandatMandataire>(x => x.ClePersonne == request.ClePersonne).Where<GenMandatGenMandatMandataire>(x => x.CleSociete == request.CleSociete).Where<GenMandatGenMandatMandataire>(x => x.CleSecteur == request.CleSecteur).Where<GenMandatGenMandatMandataire>(x => x.CleService == request.CleService).Select(request.Fields);

			var entity = Db.Single(q);
			if (entity == null)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenMandatMandataire), request.Id));
			}

			return entity;
		}

	}
}
