//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using ServiceStack;
using ServiceStack.OrmLite;
using Tmpi.Pyrene.Services.ServiceModel;
using Tmpi.Pyrene.Services.ServiceModel.Types;
using Tmpi.Pyrene.Infrastructure;

namespace Tmpi.Pyrene.Services.ServiceInterface
{
	/// <summary>
	/// Service qui traite les requêtes sur les ressources <see cref="GenService"/>.
	/// </summary>
	public partial class GenServiceService : Service
	{
		private static readonly object _syncLock = new object();

		/// <summary>
		/// Supprime la ressource <see cref="GenService"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public void Delete(DeleteGenService request)
		{
			int count = Db.DeleteById<GenService>(request.CleService);
			if (count == 0)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenService), request.CleService));
			}
		}

		/// <summary>
		/// Teste l'unicité d'un <see cref="GenService"/>.
		/// </summary>
		protected bool GenServiceCodServiceEstUnique(GenService model, IEnumerable<string> fields = null)
		{
			var q = Db.From<GenService>();

			if (fields != null)
			{
				var uniqueFields = new[] { nameof(GenService.CodService) };
				if (fields.Any(f => uniqueFields.Contains(f, StringComparer.OrdinalIgnoreCase)))
				{
					q = q.Join<GenService>((t1, t2) => t2.CleService == model.CleService, Db.JoinAlias("t2"));

					if (!fields.Contains(nameof(GenService.CodService), StringComparer.OrdinalIgnoreCase))
					{
						q = q.And<GenService, GenService>((t1, t2) => t1.CodService == t2.CodService);
					}
				}
				else
				{
					return true;
				}
			}
			
			if (fields == null || fields.Contains(nameof(GenService.CodService), StringComparer.OrdinalIgnoreCase))
			{
				q.Where(x => x.CodService == model.CodService);
			}

			if (model.CleService != 0)
			{
				q.Where(x => x.CleService != model.CleService);
			}


			return Db.Exists(q);
		}

		/// <summary>
		/// Ajoute la ressource <see cref="GenService"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns>Ressource <see cref="GenService"/> ajoutée.</returns>
		public GenService Post(GenService request)
		{
			long id = Db.Insert(request, selectIdentity: true);
			request.CleService = (int)id;

			return request;
		}

		/// <summary>
		/// Remplace la ressource <see cref="GenService"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public void Put(GenService request)
		{
			int count = Db.Update(request);
			if (count == 0)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenService), request.CleService));
			}
		}

		/// <summary>
		/// Retourne la ressource <see cref="GenService"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns>Ressource <see cref="GenService"/> trouvée.</returns>
		/// <exception cref="ArgumentException">La ressource ne contient pas tous les champs spécifiés.</exception>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public GenService Get(GetGenService request)
		{
            ModelDefinitionHelper.UndefinedFields<GenService>(request.Fields);

            var q = Db.From<GenService>().Where(x => x.CleService == request.CleService).Select(request.Fields);

			var entity = Db.Single(q);
			if (entity == null)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenService), request.CleService));
			}

			return entity;
		}

		/// <summary>
		/// Met à jour la ressource <see cref="GenService"/> spécifiée dans la requête.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <exception cref="ArgumentNullException"></exception>
		/// <exception cref="ArgumentException">La ressource ne contient pas tous les champs spécifiés.</exception>
		/// <exception cref="HttpError">La ressource spécifiée est introuvable.</exception>
		public void Patch(PatchGenService request)
		{
			if (request.Fields.IsNullOrEmpty())
			{
				throw new ArgumentNullException(nameof(request.Fields));
			}

            var patchDic = request.Fields.ToDictionary(f => f.Field, f => f.Value);

            ModelDefinitionHelper.UndefinedFields<GenService>(patchDic.Keys);

			var entity = new GenService();
			PatchHelper.PopulateFromPatch(entity, patchDic);

			var q = Db.From<GenService>().Where(x => x.CleService == request.CleService).Update(patchDic.Keys);

			int count = Db.UpdateOnly(entity, q);
			if (count == 0)
			{
				throw HttpError.NotFound(
					string.Format(ServicesErrorMessages.ResourceByIdNotFound, nameof(GenService), request.CleService));
			}
		}

		/// <summary>
		/// Retourne le résultat d'une recherche.
		/// </summary>
		/// <param name="request">Requête à traiter.</param>
		/// <returns></returns>
		public List<BasicEntity> Get(SearchGenService request)
		{
			if (string.IsNullOrWhiteSpace(request.Text))
			{
				return null;
			}

            var q = Db.From<GenService>().Where(x => x.LibService.Contains(request.Text));
            if (request.Max > 0)
            {
                q = q.Limit(request.Max);
            }

            var items = Db.Select<BasicEntity>(q);
            return items;
		}

	}
}
