//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.Infrastructure;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel
{
	/// <summary>
	/// Autocomplete une entité <see cref="GenPersonne" />.
	/// </summary>
	[Route("/GenPersonne/Autocomplete", "GET", Summary = "Autocomplete une entité GenPersonne.")]
	public partial class AutocompleteGenPersonne : AutocompleteRequestBase
	{
	}
}
