//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net;
using ServiceStack;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel
{
	/// <summary>
	/// Autocomplete une ressource <see cref="GenFourn" />.
	/// </summary>
	[Route("/GenFourn/Autocomplete", HttpVerbs.Get, Summary = "Autocomplete une ressource GenFourn.")]
	public partial class AutocompleteGenFourn : AutocompleteRequestBase
	{
	}
}
