//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net;
using ServiceStack;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel
{
	/// <summary>
	/// Supprime une ressource <see cref="GenTVA" /> à partir de son Id.
	/// </summary>
    [ApiResponse(HttpStatusCode.NotFound, "La ressource GenTVA spécifiée est introuvable.")]
	[Route("/GenTVA/{Id}", HttpVerbs.Delete, Summary = "Supprime une ressource GenTVA à partir de son Id.")]
	public partial class DeleteGenTVA : DeleteByIdRequestBase<int>
	{
	}
}
