//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.Infrastructure;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[Route("/GenCompteur", "POST", Summary = "Ajoute une entité GenCompteur.")]
	[Route("/GenCompteur/{Id}", "PUT", Summary = "Remplace une entité GenCompteur à partir de son Id.")]
	partial class GenCompteur
	{
	}
}
