//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[CompositeIndex(true, nameof(CleFourn), nameof(CodIBAN))]
    [Route("/Fourn/{CleFourn}/Banque", HttpVerbs.Post, Summary = "Ajoute une ressource Banque (Fourn).")]
    [Route("/Fourn/Banque/{CleBanque}", HttpVerbs.Put, Summary = "Remplace une ressource Banque (Fourn).")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource spécifiée est introuvable.")]
    [ApiResponse(HttpStatusCode.Conflict, "La ressource spécifiée est un doublon.")]
	public partial class GenFournBanque : IAuditable
	{
		/// <summary>
		/// Identifiant unique. Clé primaire. Immutable.
		/// </summary>
		[AutoIncrement]
		[PrimaryKey]
		[ApiMember(Description = "Identifiant unique. Clé primaire. Immutable.", DataType = SwaggerDataTypes.Int, IsRequired = true, ParameterType = SwaggerParamTypes.Path, Verb = HttpVerbs.Put)]
		public int CleBanque { get; set; }

		/// <summary>
		/// Identifiant unique du fournisseur parent.
		/// </summary>
		[ForeignKey(typeof(GenFourn), OnDelete = "CASCADE")]
		[Required]
		[ApiMember(Description = "Identifiant unique du fournisseur parent.", DataType = SwaggerDataTypes.Int, IsRequired = true, ParameterType = SwaggerParamTypes.Path, Verb = HttpVerbs.Post)]
		public int CleFourn { get; set; }

		/// <summary>
		/// Code IBAN.
		/// </summary>
		[StringLength(34)]
		[Required]
		[ApiMember(Description = "Code IBAN.", DataType = SwaggerDataTypes.String, IsRequired = true)]
		public string CodIBAN { get; set; }

		/// <summary>
		/// Code BIC.
		/// </summary>
		[StringLength(11)]
		[Required]
		[ApiMember(Description = "Code BIC.", DataType = SwaggerDataTypes.String, IsRequired = true)]
		public string CodBIC { get; set; }

		/// <summary>
		/// Nom de l'établissement bancaire.
		/// </summary>
		[StringLength(200)]
		[Required]
		[ApiMember(Description = "Nom de l'établissement bancaire.", DataType = SwaggerDataTypes.String, IsRequired = true)]
		public string LibEtablissement { get; set; }

		/// <summary>
		/// Si true, les coordonnées bancaires sont celles par défaut pour le fournisseur.
		/// </summary>
		[Required]
		[ApiMember(Description = "Si true, les coordonnées bancaires sont celles par défaut pour le fournisseur.", DataType = SwaggerDataTypes.Bool, IsRequired = true)]
		public bool EstDefaut { get; set; }

		/// <summary>
		/// Date de création. Immutable.
		/// </summary>
		[Required]
		public DateTime DatCreation { get; set; }

		/// <summary>
		/// Identifiant unique de l'utilisateur responsable de la création. Immutable.
		/// </summary>
		[Required]
		public int CleCreateur { get; set; }

		/// <summary>
		/// Date de dernière modification. Immutable.
		/// </summary>
		public DateTime? DatEdition { get; set; }

		/// <summary>
		/// Identifiant unique de l'utilisateur responsable de la dernière modification. Immutable.
		/// </summary>
		public int? CleEditeur { get; set; }

	}
}
