//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.Infrastructure;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[Route("/GenFourn/Banque", "POST", Summary = "Ajoute une entité GenFournBanque.")]
	[Route("/GenFourn/Banque/{Id}", "PUT", Summary = "Remplace une entité GenFournBanque à partir de son Id.")]
	partial class GenFournBanque
	{
	}
}
