//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.Infrastructure;
using Tmpi.Pyrene.Services.ServiceModel.Types;

namespace Tmpi.Pyrene.Services.ServiceModel.Types
{
	[Route("/GenMandat", "POST", Summary = "Ajoute une entité GenMandat.")]
	[Route("/GenMandat/{Id}", "PUT", Summary = "Remplace une entité GenMandat à partir de son Id.")]
	partial class GenMandat
	{
	}
}
