//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using ServiceStack;

namespace Tmpi.Pyrene.Services.ServiceModel.Messages
{
	/// <summary>
	/// Retourne les ressources Profil (Personne).
	/// </summary>
	/// <seealso cref="GenPersonneProfil"/>
	[Route("/Personne/{ClePersonne}/Profil", HttpVerbs.Get, Summary = "Retourne les ressources Profil (Personne).")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource spécifiée est introuvable.")]
	public partial class SelectGenPersonneProfil : IReturn<List<GenPersonneProfil>>, IGet
	{
        /// <summary>
        /// Identifiant unique de l'utilisateur parent
        /// </summary>
		[ApiMember(Description = "Identifiant unique de l'utilisateur parent", DataType = SwaggerDataTypes.Int, IsRequired = true, ParameterType = SwaggerParamTypes.Path)]
		public int ClePersonne { get; set; }

		public int? Skip { get; set; }

		public int? Take { get; set; }

		public string[] Sort { get; set; }
	}
}
