//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using ServiceStack;

namespace Tmpi.Pyrene.Services.ServiceModel.Messages
{
	/// <summary>
	/// Retourne les ressources Contact (Fourn).
	/// </summary>
	/// <seealso cref="GenFournContact"/>
	[Route("/Fourn/{CleFourn}/Contact", HttpVerbs.Get, Summary = "Retourne les ressources Contact (Fourn).")]
    [ApiResponse(HttpStatusCode.NotFound, "La ressource spécifiée est introuvable.")]
	public partial class SelectGenFournContact : IReturn<List<GenFournContact>>, IGet
	{
        /// <summary>
        /// Identifiant unique du fournisseur parent
        /// </summary>
		[ApiMember(Description = "Identifiant unique du fournisseur parent", DataType = SwaggerDataTypes.Int, IsRequired = true, ParameterType = SwaggerParamTypes.Path)]
		public int CleFourn { get; set; }

		public int? Skip { get; set; }

		public int? Take { get; set; }

		public string[] Sort { get; set; }
	}
}
