// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Core.Data
{
    using Tmpi.Pyrene.Models.Entities;

    // PersonneProfil
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_PersonneProfilConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Gen_PersonneProfil>
    {
        public Gen_PersonneProfilConfiguration()
            : this("Gen")
        {
        }

        public Gen_PersonneProfilConfiguration(string schema)
        {
            ToTable(schema + ".PersonneProfil");
            HasKey(x => x.CleProfil);

            Property(x => x.CleProfil).HasColumnName(@"CleProfil").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClePersonne).HasColumnName(@"ClePersonne").IsRequired().HasColumnType("int");
            Property(x => x.CodProfil).HasColumnName(@"CodProfil").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.CleSociete).HasColumnName(@"CleSociete").IsOptional().HasColumnType("int");
            Property(x => x.CleSecteur).HasColumnName(@"CleSecteur").IsOptional().HasColumnType("int");
            Property(x => x.CleService).HasColumnName(@"CleService").IsOptional().HasColumnType("int");

            // Foreign keys
            HasOptional(a => a.Gen_Societe).WithMany(b => b.Gen_PersonneProfil).HasForeignKey(c => c.CleSociete).WillCascadeOnDelete(false); // FK_PersonneProfil_CleSociete
            HasOptional(a => a.Gen_SocieteSecteur).WithMany(b => b.Gen_PersonneProfil).HasForeignKey(c => c.CleSecteur).WillCascadeOnDelete(false); // FK_PersonneProfil_CleSecteur
            HasOptional(a => a.Gen_SocieteService).WithMany(b => b.Gen_PersonneProfil).HasForeignKey(c => c.CleService).WillCascadeOnDelete(false); // FK_PersonneProfil_CleService
            HasRequired(a => a.Gen_Personne).WithMany(b => b.Gen_PersonneProfil).HasForeignKey(c => c.ClePersonne); // FK_PersonneProfil_ClePersonne
        }
    }

}
// </auto-generated>
