// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Tmpi.Pyrene.Core.Data
{
    using Tmpi.Pyrene.Models.Entities;

    // Personne
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.21.1.0")]
    public class Gen_PersonneConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Gen_Personne>
    {
        public Gen_PersonneConfiguration()
            : this("Gen")
        {
        }

        public Gen_PersonneConfiguration(string schema)
        {
            ToTable(schema + ".Personne");
            HasKey(x => x.ClePersonne);

            Property(x => x.ClePersonne).HasColumnName(@"ClePersonne").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CodPersonne).HasColumnName(@"CodPersonne").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.NomPersonne).HasColumnName(@"NomPersonne").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.PrePersonne).HasColumnName(@"PrePersonne").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.TxtPersonne).HasColumnName(@"TxtPersonne").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            Property(x => x.EstActif).HasColumnName(@"EstActif").IsRequired().HasColumnType("bit");
            Property(x => x.DatCreation).HasColumnName(@"DatCreation").IsRequired().HasColumnType("datetime");
            Property(x => x.DatModif).HasColumnName(@"DatModif").IsRequired().HasColumnType("datetime");
            Property(x => x.CodExterne).HasColumnName(@"CodExterne").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.TypGenre).HasColumnName(@"TypGenre").IsOptional().HasColumnType("tinyint");
            Property(x => x.NumTelep).HasColumnName(@"NumTelep").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(25);
            Property(x => x.NumEmail).HasColumnName(@"NumEmail").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
        }
    }

}
// </auto-generated>
