//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.ServiceModel.Types
{
	
	public partial class GenFournBanque : IHasId<int>
	{
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set;}
         [References(typeof(GenFourn))]
        [Required]
        public int CleGenFourn { get; set;}
        [Required]
        public string LibBanque { get; set;}
        [Required]
        public string RibBanque { get; set;}
        [Required]
        public string RibGuichet { get; set;}
        [Required]
        public string RibCompte { get; set;}
        [Required]
        public string RibCle { get; set;}
        [Required]
        public bool EstDefaut { get; set;}
}
}
