//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using ServiceStack;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace Tmpi.Pyrene.ServiceModel.Types
{
	[Route("/GenSecteur", "POST", Summary = "Ajoute une entité GenSecteur.")]
	[Route("/GenSecteur/{Id}", "PUT", Summary = "Remplace une entité GenSecteur.")]
	public partial class GenSecteur : IHasId<int>,
		IAuditable,
		IHasCodLibTxt
	{
		[AutoIncrement]
		public int Id { get; set; }

		[StringLength(100)]
		[Required]
		[Index(true)]
		public string CodObjet { get; set; }

		[StringLength(200)]
		[Required]
		[Index]
		public string LibObjet { get; set; }

		[StringLength(500)]
		public string TxtObjet { get; set; }

		[Required]
		public bool EstActif { get; set; }

		[Required]
		public DateTime DatCreation { get; set; }

		[Required]
		public DateTime DatModif { get; set; }

		[StringLength(100)]
		public string CodExterne { get; set; }

		[ForeignKey(typeof(GenSociete), OnDelete = "CASCADE")]
		[Required]
		[Index]
		public int CleGenSociete { get; set; }

		[StringLength(200)]
		public string AdrRue { get; set; }

		[StringLength(10)]
		public string AdrCode { get; set; }

		[StringLength(100)]
		public string AdrVille { get; set; }

		[StringLength(100)]
		public string AdrPays { get; set; }

		[StringLength(25)]
		public string NumTelep { get; set; }

		[StringLength(25)]
		public string NumFax { get; set; }

		[StringLength(100)]
		public string NumEmail { get; set; }

	}
}
