//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

import { Injectable } from '@angular/core';

import { ServiceClient } from '/service-client';
import { SelectPersonne, SelectPersonneResponse, DeletePersonne } from '/dtos';

@Injectable()
export class PersonneService extends ServiceClient {
	selectPersonne(fields: string, sort: string[], skip?: number, take?: number): Promise<SelectPersonneResponse> {
		const req = new SelectPersonne();
		req.Fields = fields;
		req.Sort = sort;
		if (skip) {
			req.Skip = skip;
		}
		if (take) {
			req.Take = take;
		}

		return this.client.get(req);
	}

	deletePersonne(id: number): Promise<void> {
		const req = new DeletePersonne();
		req.ClePersonne = id;

		return this.client.delete(req);
	}

}
