//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

import { Component, OnInit } from '@angular/core';

import { PagedData } from '../paged-data';
import { TVAService } from './tva.service';
import { TVA } from '/dtos';

@Component({
	selector: 'tva-list',
	templateUrl: 'tva-list.component.html',
	providers: [TVAService]
})
export class TVAListComponent implements OnInit {
	tVA: PagedData<TVA> = {
		sort: 'LibTVA',
		pageIndex: 0,
		pageSize: 20
	}

	constructor(private tVAService: TVAService) {
	}

	ngOnInit() {
		this.loadTVA();
	}

	loadTVA(): void {
		const fields = 'CodTVA,LibTVA,EstActif';
		const skip = this.tVA.pageIndex * this.tVA.pageSize;
		this.tVAService.selectTVA(fields, [this.tVA.sort], skip, this.tVA.pageSize)
			.then(r => this.tVA.data = r.Results);
	}

	deleteTVA(id: number): void {
		this.tVAService.deleteTVA(id);
	}
}
