CREATE TABLE [STO].[TVA]
(
    [CleTVA] INT IDENTITY NOT NULL,
    [CodTVA] VARCHAR(100) NOT NULL,
    [LibTVA] VARCHAR(200) NOT NULL,
    [TxtTVA] VARCHAR(500) NULL,
    [EstActif] BIT NOT NULL,
    [DatCreation] DATETIME NOT NULL,
    [DatModif] DATETIME NOT NULL,
    [CodExterne] VARCHAR(100) NULL,
    [TauTVA] DECIMAL(5,2) NOT NULL,
    CONSTRAINT [PK_TVA] PRIMARY KEY ([CleTVA]),
    CONSTRAINT [UN_TVA_CodTVA] UNIQUE ([CodTVA])
);

GO

CREATE INDEX [IX_TVA_LibTVA] ON [STO].[TVA] ([LibTVA]);
