//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

import { Injectable } from '@angular/core';
import { JsonServiceClient } from 'servicestack-client';

import { AppSettings } from '../appsettings';
import { SelectCompteur, SelectCompteurResponse } from '../dtos';

@Injectable()
export class CompteurService {
	constructor(private appConfig: AppSettings) {
	}

	selectCompteur(fields: string, sort: string[], skip?: number, take?: number): Promise<SelectCompteurResponse> {
		const req = new SelectCompteur();
		req.Fields = fields;
		req.Sort = sort;
		if (skip) {
			req.Skip = skip;
		}
		if (take) {
			req.Take = take;
		}

		const client = new JsonServiceClient('');
		return client.get(req);
	}
}
