//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.ServiceModel.Types;

namespace Tmpi.Pyrene.ServiceModel.Messages
{
	/// <summary>
	/// Ajoute ou modifie une entité <see cref="GenCompteur" />.
	/// </summary>
	[Route("/GenCompteur", "POST", Summary = "Ajoute une entité GenCompteur.")]
	[Route("/GenCompteur/{Id}", "PUT", Summary = "Modifie une entité GenCompteur.")]
	public partial class SaveGenCompteur : SaveRequestBase<GenCompteur>
	{
	}
}
