//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using Tmpi.Pyrene.ServiceModel.Types;

namespace Tmpi.Pyrene.ServiceModel.Messages
{
	/// <summary>
	/// Ajoute ou modifie une entité <see cref="GenMandat" />.
	/// </summary>
	[Route("/GenMandat", "POST", Summary = "Ajoute une entité GenMandat.")]
	[Route("/GenMandat/{Id}", "PUT", Summary = "Modifie une entité GenMandat.")]
	public partial class SaveGenMandat : SaveRequestBase<GenMandat>
	{
	}
}
