//------------------------------------------------------------------------------
// <auto-generated>
// Ce code a été généré par un outil.
//
// Les modifications apportées à ce fichier peuvent provoquer un comportement
// incorrect et seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack.FluentValidation;
using Tmpi.Pyrene.ServiceModel;
using Tmpi.Pyrene.ServiceModel.Types;

namespace Tmpi.Pyrene.ServiceInterface
{
	/// <summary>
	/// Validation pour la requête <see cref="Exercice"/>.
	/// </summary>
	public partial class ExerciceValidator : AbstractValidator<Exercice>
	{
		/// <summary>
		/// Initialise une nouvelle instance de la classe <see cref="ExerciceValidator" />.
		/// </summary>
		public ExerciceValidator()
		{
			RuleFor(x => x.CodExercice)
				.NotEmpty()
				.Length(0, 100);
			RuleFor(x => x.LibExercice)
				.NotEmpty()
				.Length(0, 200);
			RuleFor(x => x.TxtExercice)
				.Length(0, 500);
			RuleFor(x => x.CodExterne)
				.Length(0, 100);

			SetRules();
		}

		/// <summary>
		/// Définit des règles de validation supplémentaires.
		/// </summary>
		partial void SetRules();
	}
}
