//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;
using ServiceStack;
using ServiceStack.OrmLite;
using Tmpi.Pyrene.ServiceModel.Types;
using Tmpi.Pyrene.ServiceModel.Messages;

namespace Tmpi.Pyrene.ServiceInterface
{
    [Authenticate]
	public partial class GenSocieteService : Service
	{
        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
		public List<string> Get(AutocompleteGenSociete request)
		{
            if (string.IsNullOrWhiteSpace(request.Text))
            {
                return null;
            }

            var q1 = Db.From<GenCompteur>().Select(c => c.CodObjet).Where(c => c.CodObjet.Contains(request.Text));
            var q2 = Db.From<GenCompteur>().Select(c => c.LibObjet).Where(c => c.LibObjet.Contains(request.Text));

			return null;
		}

        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
		public void Delete(DeleteGenSociete request)
		{
			int count = Db.DeleteById<GenSociete>(request.Id);
			if (count == 0)
			{
				throw HttpError.NotFound(
					string.Format(ErrorMessages.EntityByIdNotFound, nameof(GenSociete), request.Id));
			}
		}

        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
		public GenSociete Get(GetGenSociete request)
		{
            var entity = Db.SingleById<GenSociete>(request.Id);
			if (entity == null)
			{
				throw HttpError.NotFound(
					string.Format(ErrorMessages.EntityByIdNotFound, nameof(GenSociete), request.Id));
			}
			return entity;
		}

        /// <summary>
        /// 
        /// </summary>
        /// <param name="request"></param>
		public void Any(SaveGenSociete request)
		{
			if (request.Id == 0)
            {
                Db.Insert(request.Entity);
            }
            else
            {
                Db.Update(request.Entity);
            }
		}

	}
}
